-- HA Marketing - Account Security Upgrade
-- Run once in Supabase SQL Editor.
create extension if not exists pgcrypto;

alter table public.profiles add column if not exists contact_email text;
alter table public.profiles add column if not exists contact_email_verified boolean not null default false;
alter table public.profiles add column if not exists phone_verified boolean not null default false;
alter table public.profiles add column if not exists username_changed_at timestamptz;
alter table public.profiles add column if not exists pin_hash text;
alter table public.profiles add column if not exists pin_updated_at timestamptz;

create unique index if not exists profiles_username_lower_uq on public.profiles(lower(username)) where username is not null;
create unique index if not exists profiles_contact_email_lower_uq on public.profiles(lower(contact_email)) where contact_email is not null;

create or replace function public.enforce_username_change_cooldown()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if old.username is distinct from new.username then
    if old.username_changed_at is not null and old.username_changed_at > now()-interval '30 days' and not public.is_super_admin() then
      raise exception 'يمكن تغيير المعرف مرة واحدة كل 30 يوم';
    end if;
    new.username_changed_at=now();
  end if;
  return new;
end$$;
drop trigger if exists trg_profiles_username_cooldown on public.profiles;
create trigger trg_profiles_username_cooldown before update of username on public.profiles
for each row execute function public.enforce_username_change_cooldown();

create or replace function public.set_my_security_pin(p_pin text)
returns void language plpgsql security definer set search_path=public as $$
begin
 if auth.uid() is null then raise exception 'غير مسجل'; end if;
 if p_pin !~ '^[0-9]{6}$' then raise exception 'الرمز الخاص يجب أن يكون 6 أرقام'; end if;
 update public.profiles set pin_hash=crypt(p_pin,gen_salt('bf')),pin_updated_at=now() where id=auth.uid();
end$$;
grant execute on function public.set_my_security_pin(text) to authenticated;

create or replace function public.verify_my_security_pin(p_pin text)
returns boolean language sql security definer set search_path=public as $$
 select coalesce((select pin_hash=crypt(p_pin,pin_hash) from public.profiles where id=auth.uid()),false)
$$;
grant execute on function public.verify_my_security_pin(text) to authenticated;

create table if not exists public.account_verification_challenges(
 id uuid primary key default gen_random_uuid(),
 user_id uuid references auth.users(id) on delete cascade,
 phone text,
 email text,
 channel text not null check(channel in('whatsapp','email')),
 code_hash text not null,
 attempts int not null default 0,
 max_attempts int not null default 3,
 expires_at timestamptz not null default now()+interval '5 minutes',
 consumed_at timestamptz,
 created_at timestamptz not null default now()
);
create index if not exists account_verification_user_idx on public.account_verification_challenges(user_id,channel,created_at desc);
alter table public.account_verification_challenges enable row level security;
drop policy if exists "own verification challenges read" on public.account_verification_challenges;
create policy "own verification challenges read" on public.account_verification_challenges for select to authenticated using(user_id=auth.uid());
-- INSERT/UPDATE intentionally server-only. Edge Functions use service role.

create table if not exists public.account_security_events(
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 event_type text not null,
 details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
alter table public.account_security_events enable row level security;
drop policy if exists "own security events read" on public.account_security_events;
create policy "own security events read" on public.account_security_events for select to authenticated using(user_id=auth.uid());
grant select on public.account_security_events to authenticated;
