-- HA Marketing: in-app notifications + admin controls (idempotent)

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  department text,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.notifications add column if not exists order_id bigint references public.orders(id) on delete cascade;
alter table public.notifications add column if not exists kind text;

alter table public.notifications enable row level security;
drop policy if exists "users read own notifications" on public.notifications;
create policy "users read own notifications" on public.notifications for select to authenticated using(auth.uid()=user_id);
drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications" on public.notifications for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

create or replace function public.notify_service_order_created()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.notifications(user_id,department,title,message,order_id,kind)
  select p.id,new.department,'طلب جديد','وصل طلب جديد: '||coalesce(new.order_type,'خدمة'),new.id,'order_new'
  from public.profiles p join public.employee_roles r on r.id=p.employee_role_id
  where p.account_type='employee' and p.employee_status='approved' and r.is_active=true and r.department=new.department;
  return new;
end;$$;
drop trigger if exists trg_notify_service_order_created on public.orders;
create trigger trg_notify_service_order_created after insert on public.orders for each row execute function public.notify_service_order_created();

create or replace function public.notify_service_order_status()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_title text; v_msg text;
begin
  if new.status is distinct from old.status then
    v_title:='تحديث الطلب';
    v_msg:=case new.status
      when 'accepted' then 'تم قبول طلبك.'
      when 'on_the_way' then 'الموظف في الطريق إليك.'
      when 'completed' then 'تم إكمال الخدمة.'
      when 'cancelled' then 'تم إلغاء الطلب.'
      else 'تغيرت حالة الطلب إلى: '||new.status end;
    insert into public.notifications(user_id,department,title,message,order_id,kind)
    values(new.customer_id,new.department,v_title,v_msg,new.id,'order_status');
    if new.assigned_employee_id is not null then
      insert into public.notifications(user_id,department,title,message,order_id,kind)
      values(new.assigned_employee_id,new.department,'تحديث الطلب','حالة الطلب #'||new.id||': '||new.status,new.id,'employee_order_status');
    end if;
  end if;
  return new;
end;$$;
drop trigger if exists trg_notify_service_order_status on public.orders;
create trigger trg_notify_service_order_status after update of status on public.orders for each row execute function public.notify_service_order_status();

-- Admin helpers. An admin is a profile whose account_type = 'admin'.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and account_type='admin');
$$;

drop policy if exists "admins read profiles" on public.profiles;
create policy "admins read profiles" on public.profiles for select to authenticated using(public.is_admin());
drop policy if exists "admins update profiles" on public.profiles;
create policy "admins update profiles" on public.profiles for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admins read all orders" on public.orders;
create policy "admins read all orders" on public.orders for select to authenticated using(public.is_admin());

create or replace function public.admin_set_employee_status(p_user_id uuid,p_status text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Not allowed'; end if;
  if p_status not in ('pending','approved','rejected') then raise exception 'Invalid status'; end if;
  update public.profiles set employee_status=p_status where id=p_user_id and account_type='employee';
  if not found then raise exception 'Employee not found'; end if;
  insert into public.notifications(user_id,title,message,kind)
  values(p_user_id,'حالة حساب الموظف',case p_status when 'approved' then 'تمت الموافقة على حساب الموظف.' when 'rejected' then 'تم رفض حساب الموظف.' else 'تم إرجاع الحساب إلى المراجعة.' end,'employee_approval');
end;$$;
grant execute on function public.admin_set_employee_status(uuid,text) to authenticated;

do $$ begin alter publication supabase_realtime add table public.notifications; exception when duplicate_object then null; end $$;
