
const db=supabase.createClient('https://ubayrhtshgtgggxprrek.supabase.co','sb_publishable_p3108yoDkdJTLqVXhkvmBg_KVqe-1ll',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'ha-marketing-auth'}});
function tab(id,b){document.querySelectorAll('.lesson').forEach(x=>x.classList.remove('show'));document.getElementById(id).classList.add('show');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
async function ai(prompt,out){const el=document.getElementById(out);el.innerHTML='<span class="loader"></span> جاري العمل...';let {data:{session}}=await db.auth.getSession();if(!session){location.href='login.html?next=study-language.html';return}const body={message:prompt};try{let result=null;const inv=await db.functions.invoke('ai-assistant',{body});if(!inv.error&&inv.data){result=inv.data}else{const c=new AbortController(),t=setTimeout(()=>c.abort(),30000);const r=await fetch('https://ubayrhtshgtgggxprrek.supabase.co/functions/v1/ai-assistant',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':'sb_publishable_p3108yoDkdJTLqVXhkvmBg_KVqe-1ll'},body:JSON.stringify(body),signal:c.signal});clearTimeout(t);result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||'HTTP '+r.status)}const answer=result?.answer||result?.data?.answer;if(!answer)throw new Error(result?.error||'لم يصل جواب من المساعد');el.textContent=answer}catch(e){console.error(e);el.textContent='تعذر تشغيل المساعد حالياً: '+(e?.message||'حدث خطأ غير معروف')}}
function askLearn(x){learnQ.value=x;learn()}
function learn(){const q=learnQ.value.trim()||'اعطني درس اليوم';ai(`أنت مدرس لغة إنجليزية للعرب. المستوى: ${level.value}. الموضوع: ${topic.value}. الطلب: ${q}. اشرح بالعربية مع أمثلة إنجليزية وترجمة ونطق تقريبي عند الحاجة، واجعل الدرس عملياً ومختصراً.`,`learnOut`)}
function translateText(){const text=txt.value.trim();if(!text)return;const source=from.value==='تحديد تلقائي'?'حدّد لغة النص تلقائياً':`لغة المصدر هي ${from.value}`;ai(`${source}. ترجم النص التالي إلى ${to.value}. أرجع الترجمة فقط بدون شرح أو مقدمات، مع الحفاظ على المعنى والأسماء والأرقام وتنسيق الأسطر قدر الإمكان:
${text}`,`transOut`)}
function swapLanguages(){if(from.value==='تحديد تلقائي'){from.value=to.value;to.value=from.value==='العربية'?'الإنجليزية':'العربية';return}const a=from.value,b=to.value;from.value=b;to.value=a}
async function copyTranslation(){const t=transOut.textContent.trim();if(!t||t==='—')return;try{await navigator.clipboard.writeText(t)}catch(_e){const x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove()}}
function clearTranslation(){txt.value='';transOut.textContent='—';txt.focus()}
