-- HA Marketing: private/group chat + managed news/content
create table if not exists public.chat_threads(
 id uuid primary key default gen_random_uuid(), type text not null check(type in ('private','group')),
 title text, image_url text, created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.chat_members(
 thread_id uuid references public.chat_threads(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade,
 role text not null default 'member' check(role in ('owner','admin','member')),
 muted boolean not null default false, last_read_at timestamptz default now(), joined_at timestamptz default now(),
 primary key(thread_id,user_id)
);
create table if not exists public.chat_messages(
 id bigint generated by default as identity primary key, thread_id uuid not null references public.chat_threads(id) on delete cascade,
 sender_id uuid not null references auth.users(id) on delete cascade, body text not null check(length(body)<=4000),
 reply_to bigint references public.chat_messages(id) on delete set null, created_at timestamptz not null default now(), edited_at timestamptz
);
create index if not exists chat_messages_thread_time on public.chat_messages(thread_id,created_at);

create or replace function public.start_private_chat(other_user uuid) returns uuid language plpgsql security definer set search_path=public as $$
declare tid uuid;
begin
 if other_user=auth.uid() then raise exception 'لا يمكن بدء محادثة مع نفسك'; end if;
 select t.id into tid from chat_threads t join chat_members a on a.thread_id=t.id and a.user_id=auth.uid() join chat_members b on b.thread_id=t.id and b.user_id=other_user where t.type='private' limit 1;
 if tid is null then insert into chat_threads(type,created_by) values('private',auth.uid()) returning id into tid; insert into chat_members(thread_id,user_id,role) values(tid,auth.uid(),'owner'),(tid,other_user,'member'); end if;
 return tid;
end$$;
grant execute on function public.start_private_chat(uuid) to authenticated;

create or replace function public.create_group_chat(p_title text,p_members uuid[]) returns uuid language plpgsql security definer set search_path=public as $$
declare tid uuid; u uuid;
begin
 if trim(coalesce(p_title,''))='' then raise exception 'اسم الكروب مطلوب'; end if;
 insert into chat_threads(type,title,created_by) values('group',trim(p_title),auth.uid()) returning id into tid;
 insert into chat_members(thread_id,user_id,role) values(tid,auth.uid(),'owner');
 foreach u in array coalesce(p_members,array[]::uuid[]) loop if u<>auth.uid() then insert into chat_members(thread_id,user_id,role) values(tid,u,'member') on conflict do nothing; end if; end loop;
 return tid;
end$$;
grant execute on function public.create_group_chat(text,uuid[]) to authenticated;

alter table chat_threads enable row level security; alter table chat_members enable row level security; alter table chat_messages enable row level security;
drop policy if exists "thread members read" on chat_threads; create policy "thread members read" on chat_threads for select to authenticated using(exists(select 1 from chat_members m where m.thread_id=id and m.user_id=auth.uid()));
drop policy if exists "members read members" on chat_members; create policy "members read members" on chat_members for select to authenticated using(exists(select 1 from chat_members me where me.thread_id=thread_id and me.user_id=auth.uid()));
drop policy if exists "members update self" on chat_members; create policy "members update self" on chat_members for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "messages member read" on chat_messages; create policy "messages member read" on chat_messages for select to authenticated using(exists(select 1 from chat_members m where m.thread_id=chat_messages.thread_id and m.user_id=auth.uid()));
drop policy if exists "messages member send" on chat_messages; create policy "messages member send" on chat_messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from chat_members m where m.thread_id=chat_messages.thread_id and m.user_id=auth.uid()));
drop policy if exists "messages own edit" on chat_messages; create policy "messages own edit" on chat_messages for update to authenticated using(sender_id=auth.uid()) with check(sender_id=auth.uid());
drop policy if exists "messages own delete" on chat_messages; create policy "messages own delete" on chat_messages for delete to authenticated using(sender_id=auth.uid());
grant select on chat_threads,chat_members,chat_messages to authenticated; grant insert,update,delete on chat_messages to authenticated; grant update on chat_members to authenticated;

create table if not exists public.content_posts(
 id bigint generated by default as identity primary key, section text not null, category text not null default 'عام', title text not null,
 summary text, body text, image_url text, source_name text, source_url text, is_breaking boolean not null default false,
 is_featured boolean not null default false, is_active boolean not null default true, published_at timestamptz not null default now(),
 created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists content_posts_section_time on content_posts(section,is_active,published_at desc);
alter table content_posts enable row level security;
drop policy if exists "content public read" on content_posts; create policy "content public read" on content_posts for select using(is_active=true or public.is_super_admin());
drop policy if exists "content admin insert" on content_posts; create policy "content admin insert" on content_posts for insert to authenticated with check(public.is_super_admin());
drop policy if exists "content admin update" on content_posts; create policy "content admin update" on content_posts for update to authenticated using(public.is_super_admin()) with check(public.is_super_admin());
drop policy if exists "content admin delete" on content_posts; create policy "content admin delete" on content_posts for delete to authenticated using(public.is_super_admin());
grant select on content_posts to anon,authenticated; grant insert,update,delete on content_posts to authenticated;
