-- HA Marketing - Core Marketplace Roles / Seller / Provider / Transport / Study Library
-- شغّله مرة واحدة بعد رفع النسخة.

create table if not exists public.marketplace_applications(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 role_type text not null check(role_type in ('seller','service_provider','taxi_driver','delivery_driver')),
 display_name text not null,
 phone text,
 governorate text,
 address text,
 details text,
 document_url text,
 status text not null default 'pending' check(status in ('pending','approved','rejected','suspended')),
 admin_note text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(user_id,role_type)
);

alter table public.shop_businesses add column if not exists owner_user_id uuid references auth.users(id) on delete set null;
alter table public.products add column if not exists seller_user_id uuid references auth.users(id) on delete set null;
alter table public.products add column if not exists business_id bigint references public.shop_businesses(id) on delete set null;

alter table public.service_providers add column if not exists owner_user_id uuid references auth.users(id) on delete set null;
create table if not exists public.service_availability(
 id bigint generated by default as identity primary key,
 provider_id bigint not null references public.service_providers(id) on delete cascade,
 day_of_week int not null check(day_of_week between 0 and 6),
 start_time time not null, end_time time not null,
 is_active boolean not null default true,
 unique(provider_id,day_of_week,start_time,end_time)
);
alter table public.service_requests add column if not exists service_mode text default 'customer_location' check(service_mode in ('customer_location','provider_location'));
alter table public.service_requests add column if not exists provider_note text;

create table if not exists public.transport_profiles(
 user_id uuid primary key references auth.users(id) on delete cascade,
 role_type text not null check(role_type in ('taxi_driver','delivery_driver')),
 full_name text not null, phone text, vehicle_type text, vehicle_model text, vehicle_color text, plate_number text,
 governorate text, photo_url text, document_url text,
 status text not null default 'pending' check(status in ('pending','approved','rejected','suspended')),
 is_online boolean not null default false,
 rating numeric(3,2) not null default 0,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.transport_delivery_otps(
 id bigint generated by default as identity primary key,
 delivery_ref text not null unique,
 customer_id uuid not null references auth.users(id) on delete cascade,
 driver_id uuid references auth.users(id) on delete set null,
 otp_code text not null,
 verified_at timestamptz,
 created_at timestamptz not null default now()
);

create table if not exists public.study_materials(
 id bigint generated by default as identity primary key,
 stage text not null, grade text, subject text not null,
 title text not null, material_type text not null default 'lesson' check(material_type in ('book','notes','lesson','video','questions','exam')),
 description text, file_url text, external_url text,
 is_active boolean not null default true,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);

create or replace function public.has_approved_role(p_role text)
returns boolean language sql stable security definer set search_path=public as $$
 select public.is_super_admin() or exists(
   select 1 from public.marketplace_applications m
   where m.user_id=auth.uid() and m.role_type=p_role and m.status='approved'
 );
$$;
grant execute on function public.has_approved_role(text) to authenticated;

alter table public.marketplace_applications enable row level security;
alter table public.service_availability enable row level security;
alter table public.transport_profiles enable row level security;
alter table public.transport_delivery_otps enable row level security;
alter table public.study_materials enable row level security;

-- applications
 drop policy if exists "market apps own read" on public.marketplace_applications;
create policy "market apps own read" on public.marketplace_applications for select to authenticated using(user_id=auth.uid() or public.is_super_admin());
 drop policy if exists "market apps own insert" on public.marketplace_applications;
create policy "market apps own insert" on public.marketplace_applications for insert to authenticated with check(user_id=auth.uid());
 drop policy if exists "market apps own update" on public.marketplace_applications;
create policy "market apps own update" on public.marketplace_applications for update to authenticated using(user_id=auth.uid() or public.is_super_admin()) with check(user_id=auth.uid() or public.is_super_admin());

-- seller owns store/products after approval
 drop policy if exists "seller own businesses" on public.shop_businesses;
create policy "seller own businesses" on public.shop_businesses for all to authenticated using(owner_user_id=auth.uid() and public.has_approved_role('seller')) with check(owner_user_id=auth.uid() and public.has_approved_role('seller'));
 drop policy if exists "seller own products" on public.products;
create policy "seller own products" on public.products for all to authenticated using(seller_user_id=auth.uid() and public.has_approved_role('seller')) with check(seller_user_id=auth.uid() and public.has_approved_role('seller'));

-- provider owns profile/availability and can process own requests
 drop policy if exists "provider own profile" on public.service_providers;
create policy "provider own profile" on public.service_providers for all to authenticated using(owner_user_id=auth.uid() and public.has_approved_role('service_provider')) with check(owner_user_id=auth.uid() and public.has_approved_role('service_provider'));
 drop policy if exists "provider own availability" on public.service_availability;
create policy "provider own availability" on public.service_availability for all to authenticated using(exists(select 1 from public.service_providers p where p.id=provider_id and p.owner_user_id=auth.uid())) with check(exists(select 1 from public.service_providers p where p.id=provider_id and p.owner_user_id=auth.uid()));
 drop policy if exists "provider request read" on public.service_requests;
create policy "provider request read" on public.service_requests for select to authenticated using(customer_id=auth.uid() or public.is_app_admin() or exists(select 1 from public.service_providers p where p.id=provider_id and p.owner_user_id=auth.uid()));
 drop policy if exists "provider request update" on public.service_requests;
create policy "provider request update" on public.service_requests for update to authenticated using(customer_id=auth.uid() or public.is_app_admin() or exists(select 1 from public.service_providers p where p.id=provider_id and p.owner_user_id=auth.uid())) with check(customer_id=auth.uid() or public.is_app_admin() or exists(select 1 from public.service_providers p where p.id=provider_id and p.owner_user_id=auth.uid()));

-- transport profile
 drop policy if exists "transport profile own" on public.transport_profiles;
create policy "transport profile own" on public.transport_profiles for select to authenticated using(user_id=auth.uid() or public.is_super_admin());
 drop policy if exists "transport profile insert" on public.transport_profiles;
create policy "transport profile insert" on public.transport_profiles for insert to authenticated with check(user_id=auth.uid());
 drop policy if exists "transport profile update" on public.transport_profiles;
create policy "transport profile update" on public.transport_profiles for update to authenticated using(user_id=auth.uid() or public.is_super_admin()) with check(user_id=auth.uid() or public.is_super_admin());

-- otp: owner + assigned driver + admin
 drop policy if exists "delivery otp read" on public.transport_delivery_otps;
create policy "delivery otp read" on public.transport_delivery_otps for select to authenticated using(customer_id=auth.uid() or driver_id=auth.uid() or public.is_super_admin());
 drop policy if exists "delivery otp insert" on public.transport_delivery_otps;
create policy "delivery otp insert" on public.transport_delivery_otps for insert to authenticated with check(customer_id=auth.uid() or public.is_super_admin());
 drop policy if exists "delivery otp update" on public.transport_delivery_otps;
create policy "delivery otp update" on public.transport_delivery_otps for update to authenticated using(customer_id=auth.uid() or driver_id=auth.uid() or public.is_super_admin()) with check(customer_id=auth.uid() or driver_id=auth.uid() or public.is_super_admin());

-- study library
 drop policy if exists "study materials public" on public.study_materials;
create policy "study materials public" on public.study_materials for select using(is_active=true or public.is_super_admin());
 drop policy if exists "study materials admin" on public.study_materials;
create policy "study materials admin" on public.study_materials for all to authenticated using(public.is_super_admin()) with check(public.is_super_admin());

grant select,insert,update,delete on public.marketplace_applications,public.service_availability,public.transport_profiles,public.transport_delivery_otps,public.study_materials to authenticated;
grant select on public.study_materials to anon;

-- helper: approve an application and prepare role profile
create or replace function public.admin_review_marketplace_application(p_id bigint,p_status text,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare a public.marketplace_applications;
begin
 if not public.is_super_admin() then raise exception 'غير مصرح'; end if;
 if p_status not in ('approved','rejected','suspended','pending') then raise exception 'حالة غير صحيحة'; end if;
 update public.marketplace_applications set status=p_status,admin_note=p_note,updated_at=now() where id=p_id returning * into a;
 if a.id is null then raise exception 'الطلب غير موجود'; end if;
 if a.role_type in ('taxi_driver','delivery_driver') then
   insert into public.transport_profiles(user_id,role_type,full_name,phone,governorate,status)
   values(a.user_id,a.role_type,a.display_name,a.phone,a.governorate,p_status)
   on conflict(user_id) do update set status=excluded.status,role_type=excluded.role_type,full_name=excluded.full_name,phone=excluded.phone,governorate=excluded.governorate,updated_at=now();
 end if;
end;$$;
grant execute on function public.admin_review_marketplace_application(bigint,text,text) to authenticated;
