-- HA Marketing consolidated remaining backend setup.
-- Existing service/push/shop SQL already executed separately can safely coexist with this file.

-- Chat: normalize schema, secure authenticated access, and store voice media in Storage.
alter table if exists public.messages add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table if exists public.messages add column if not exists message_type text not null default 'text';
alter table if exists public.messages add column if not exists file_url text;
alter table if exists public.messages add column if not exists created_at timestamptz not null default now();

alter table if exists public.messages enable row level security;
drop policy if exists "public read messages" on public.messages;
drop policy if exists "public insert messages" on public.messages;
drop policy if exists "authenticated read messages" on public.messages;
create policy "authenticated read messages" on public.messages for select to authenticated using(true);
drop policy if exists "authenticated insert messages" on public.messages;
create policy "authenticated insert messages" on public.messages for insert to authenticated with check(user_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('chat-media','chat-media',true,10485760,array['audio/webm','audio/ogg','audio/mp4','image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=true,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "chat media authenticated upload" on storage.objects;
create policy "chat media authenticated upload" on storage.objects for insert to authenticated
with check(bucket_id='chat-media' and (storage.foldername(name))[1]=auth.uid()::text);

-- Password recovery requests: because login uses synthetic @ha.local addresses,
-- a phone reset cannot be securely automated without a verified SMS/WhatsApp provider.
create table if not exists public.password_reset_requests(
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  phone text not null,
  status text not null default 'pending' check(status in('pending','verified','completed','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.password_reset_requests enable row level security;
drop policy if exists "user read reset requests" on public.password_reset_requests;
create policy "user read reset requests" on public.password_reset_requests for select to authenticated using(user_id=auth.uid() or public.is_admin());
drop policy if exists "admin manage reset requests" on public.password_reset_requests;
create policy "admin manage reset requests" on public.password_reset_requests for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- Realtime for chat. Safe if already added.
do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null; end $$;
