-- HA Marketing - remaining points final backend
-- Run once after the previously completed service/push/shop SQL.

-- Chat schema and secure authenticated messages
alter table if exists public.messages add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table if exists public.messages add column if not exists username text;
alter table if exists public.messages add column if not exists room text;
alter table if exists public.messages add column if not exists message text;
alter table if exists public.messages add column if not exists message_type text not null default 'text';
alter table if exists public.messages add column if not exists file_url text;
alter table if exists public.messages add column if not exists created_at timestamptz not null default now();

alter table public.messages enable row level security;
drop policy if exists "public read messages" on public.messages;
drop policy if exists "public insert messages" on public.messages;
drop policy if exists "authenticated read messages" on public.messages;
create policy "authenticated read messages" on public.messages for select to authenticated using(true);
drop policy if exists "authenticated insert messages" on public.messages;
create policy "authenticated insert messages" on public.messages for insert to authenticated with check(user_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('chat-media','chat-media',true,10485760,array['audio/webm','audio/ogg','audio/mp4','image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=true,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "chat media authenticated upload" on storage.objects;
create policy "chat media authenticated upload" on storage.objects for insert to authenticated
with check(bucket_id='chat-media' and (storage.foldername(name))[1]=auth.uid()::text);

-- Password reset request queue: safe public RPC, admin-managed verification
create table if not exists public.password_reset_requests(
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 phone text not null,
 status text not null default 'pending' check(status in('pending','verified','completed','rejected')),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.password_reset_requests enable row level security;
drop policy if exists "admin read reset requests" on public.password_reset_requests;
create policy "admin read reset requests" on public.password_reset_requests for select to authenticated using(public.is_admin());

create or replace function public.request_password_reset(p_phone text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_uid uuid; v_id bigint;
begin
  select id into v_uid from public.profiles where phone=p_phone limit 1;
  if v_uid is null then
    -- generic result avoids revealing whether a phone is registered
    insert into public.password_reset_requests(user_id,phone,status) values(null,p_phone,'pending') returning id into v_id;
  else
    insert into public.password_reset_requests(user_id,phone,status) values(v_uid,p_phone,'pending') returning id into v_id;
  end if;
  return v_id;
end;$$;
grant execute on function public.request_password_reset(text) to anon,authenticated;

create or replace function public.admin_set_password_reset_status(p_request_id bigint,p_status text)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.is_admin() then raise exception 'Not allowed'; end if;
 if p_status not in('pending','verified','completed','rejected') then raise exception 'Invalid status'; end if;
 update public.password_reset_requests set status=p_status,updated_at=now() where id=p_request_id;
 if not found then raise exception 'Request not found'; end if;
end;$$;
grant execute on function public.admin_set_password_reset_status(bigint,text) to authenticated;

-- Realtime chat
DO $$ begin
 alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null; end $$;
