-- HA Marketing - fixes 2026-09-04 B

-- Public-safe user search by CURRENT username only
create or replace function public.search_app_users(p_query text default '', p_limit integer default 30)
returns table(id uuid, full_name text, username text)
language sql security definer set search_path=public as $$
 select p.id,p.full_name,p.username from public.profiles p
 where p.id<>auth.uid() and p.username is not null
 and (coalesce(trim(p_query),'')='' or p.username ilike '%'||trim(p_query)||'%' or p.full_name ilike '%'||trim(p_query)||'%')
 order by case when lower(p.username)=lower(trim(p_query)) then 0 else 1 end,p.full_name nulls last limit least(greatest(coalesce(p_limit,30),1),50);
$$;
revoke all on function public.search_app_users(text,integer) from public; grant execute on function public.search_app_users(text,integer) to authenticated;

-- Student registration, works through one controlled RPC
create table if not exists public.study_students(id bigint generated by default as identity primary key,owner_user_id uuid not null references auth.users(id) on delete cascade,student_name text not null,education_level text not null,grade text,institution_name text,governorate text,area text,phone text,birth_year integer,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.study_students enable row level security;
drop policy if exists "students read own or super" on public.study_students; create policy "students read own or super" on public.study_students for select to authenticated using(owner_user_id=auth.uid() or public.is_super_admin());
drop policy if exists "students insert own" on public.study_students; create policy "students insert own" on public.study_students for insert to authenticated with check(owner_user_id=auth.uid());
drop policy if exists "students update own or super" on public.study_students; create policy "students update own or super" on public.study_students for update to authenticated using(owner_user_id=auth.uid() or public.is_super_admin()) with check(owner_user_id=auth.uid() or public.is_super_admin());
grant select,insert,update,delete on public.study_students to authenticated;
create or replace function public.register_my_student(p_student jsonb) returns bigint language plpgsql security definer set search_path=public as $$ declare v_id bigint; begin if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if; if coalesce(trim(p_student->>'student_name'),'')='' then raise exception 'اسم الطالب مطلوب'; end if; insert into public.study_students(owner_user_id,student_name,education_level,grade,institution_name,governorate,area,phone,birth_year,notes) values(auth.uid(),trim(p_student->>'student_name'),coalesce(nullif(trim(p_student->>'education_level'),''),'ابتدائي'),nullif(trim(p_student->>'grade'),''),nullif(trim(p_student->>'institution_name'),''),nullif(trim(p_student->>'governorate'),''),nullif(trim(p_student->>'area'),''),nullif(trim(p_student->>'phone'),''),nullif(p_student->>'birth_year','')::integer,nullif(trim(p_student->>'notes'),'')) returning id into v_id; return v_id; end $$;
grant execute on function public.register_my_student(jsonb) to authenticated;

-- Allow talent feed to resolve minimal author identity safely through a view-like RPC relationship fallback
-- Sports challenges
create table if not exists public.study_sports_challenges(id bigint generated by default as identity primary key,creator_id uuid not null references auth.users(id) on delete cascade,title text not null,sport text not null,details text,end_date date,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.study_sports_challenge_entries(id bigint generated by default as identity primary key,challenge_id bigint not null references public.study_sports_challenges(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,score numeric,notes text,created_at timestamptz not null default now(),unique(challenge_id,user_id));
alter table public.study_sports_challenges enable row level security; alter table public.study_sports_challenge_entries enable row level security;
drop policy if exists "sports challenges read" on public.study_sports_challenges; create policy "sports challenges read" on public.study_sports_challenges for select to anon,authenticated using(is_active=true);
drop policy if exists "sports challenges create" on public.study_sports_challenges; create policy "sports challenges create" on public.study_sports_challenges for insert to authenticated with check(creator_id=auth.uid());
drop policy if exists "sports entries read" on public.study_sports_challenge_entries; create policy "sports entries read" on public.study_sports_challenge_entries for select to authenticated using(true);
drop policy if exists "sports entries own" on public.study_sports_challenge_entries; create policy "sports entries own" on public.study_sports_challenge_entries for insert to authenticated with check(user_id=auth.uid());
grant select on public.study_sports_challenges to anon,authenticated; grant insert on public.study_sports_challenges to authenticated; grant select,insert,update on public.study_sports_challenge_entries to authenticated;
