-- HA Marketing - Remaining backend install (NO TESTS)
-- Includes: PIN security, username 30-day cooldown, service schema compatibility,
-- final shop courier customer/driver functions, and account deletion requests.

create extension if not exists pgcrypto;

-- 1) Account security remaining
alter table public.profiles add column if not exists username_changed_at timestamptz;
alter table public.profiles add column if not exists pin_hash text;
alter table public.profiles add column if not exists pin_updated_at timestamptz;

create or replace function public.enforce_username_change_cooldown()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare v_super boolean := false;
begin
  if old.username is distinct from new.username then
    select exists(
      select 1 from public.app_admins a
      where a.user_id=auth.uid() and a.is_active=true and coalesce(a.is_super_admin,false)=true
    ) into v_super;
    if old.username_changed_at is not null
       and old.username_changed_at > now()-interval '30 days'
       and not v_super then
      raise exception 'يمكن تغيير المعرف مرة واحدة كل 30 يوم';
    end if;
    new.username_changed_at=now();
  end if;
  return new;
end$$;

drop trigger if exists trg_profiles_username_cooldown on public.profiles;
create trigger trg_profiles_username_cooldown
before update of username on public.profiles
for each row execute function public.enforce_username_change_cooldown();

create or replace function public.set_my_security_pin(p_pin text)
returns void
language plpgsql
security definer
set search_path=public,extensions
as $$
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول أولاً'; end if;
  if p_pin !~ '^[0-9]{6}$' then raise exception 'الرمز الخاص يجب أن يكون 6 أرقام'; end if;
  update public.profiles
     set pin_hash=extensions.crypt(p_pin,extensions.gen_salt('bf')), pin_updated_at=now()
   where id=auth.uid();
end$$;
grant execute on function public.set_my_security_pin(text) to authenticated;

create or replace function public.verify_my_security_pin(p_pin text)
returns boolean
language sql
security definer
set search_path=public,extensions
as $$
  select coalesce((
    select pin_hash is not null and extensions.crypt(p_pin,pin_hash)=pin_hash
    from public.profiles where id=auth.uid()
  ),false)
$$;
grant execute on function public.verify_my_security_pin(text) to authenticated;

-- 2) Service marketplace compatibility with the live bootstrap schema
create table if not exists public.service_categories(
 id bigint generated by default as identity primary key,
 name text not null unique,
 icon text default '🛠️',
 description text,
 image_url text,
 sort_order integer not null default 100,
 is_active boolean not null default true,
 created_at timestamptz not null default now()
);

alter table public.service_providers add column if not exists category_id bigint references public.service_categories(id) on delete set null;
alter table public.service_providers add column if not exists name text;
alter table public.service_providers add column if not exists price_from numeric(12,2);
alter table public.service_providers add column if not exists price_note text;
alter table public.service_providers add column if not exists lat double precision;
alter table public.service_providers add column if not exists lng double precision;
alter table public.service_providers add column if not exists sort_order integer not null default 100;
update public.service_providers set name=full_name where name is null and full_name is not null;
update public.service_providers set price_from=starting_price where price_from is null and starting_price is not null;

alter table public.service_requests add column if not exists category_id bigint references public.service_categories(id) on delete set null;
alter table public.service_requests add column if not exists customer_name text;
alter table public.service_requests add column if not exists details text;
alter table public.service_requests add column if not exists preferred_date date;
alter table public.service_requests add column if not exists preferred_time text;
alter table public.service_requests add column if not exists customer_lat double precision;
alter table public.service_requests add column if not exists customer_lng double precision;
alter table public.service_requests add column if not exists cancel_reason text;
alter table public.service_requests add column if not exists updated_at timestamptz not null default now();

create table if not exists public.service_favorites(
 user_id uuid not null references auth.users(id) on delete cascade,
 provider_id bigint not null references public.service_providers(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(user_id,provider_id)
);
create table if not exists public.service_reviews(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 provider_id bigint not null references public.service_providers(id) on delete cascade,
 rating integer not null check(rating between 1 and 5),
 comment text,
 created_at timestamptz not null default now(),
 unique(user_id,provider_id)
);

alter table public.service_categories enable row level security;
alter table public.service_favorites enable row level security;
alter table public.service_reviews enable row level security;

drop policy if exists "service categories public read" on public.service_categories;
create policy "service categories public read" on public.service_categories for select using(is_active=true);
drop policy if exists "service favorites own" on public.service_favorites;
create policy "service favorites own" on public.service_favorites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "service reviews public" on public.service_reviews;
create policy "service reviews public" on public.service_reviews for select using(true);
drop policy if exists "service reviews own insert" on public.service_reviews;
create policy "service reviews own insert" on public.service_reviews for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "service reviews own update" on public.service_reviews;
create policy "service reviews own update" on public.service_reviews for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

grant select on public.service_categories,public.service_reviews to anon,authenticated;
grant select,insert,update,delete on public.service_favorites,public.service_reviews to authenticated;

insert into public.service_categories(name,icon,description,sort_order) values
('حداد','⚒️','أعمال الحدادة والأبواب والهياكل المعدنية',10),
('حلاق','💈','حلاقة وتجميل وعناية شخصية',20),
('كهربائي','⚡','تمديدات وصيانة كهربائية',30),
('سباك','🔧','صيانة وتمديدات صحية ومياه',40),
('نجار','🪚','أعمال النجارة والأثاث',50),
('تبريد وتكييف','❄️','صيانة وتركيب أجهزة التبريد والتكييف',60),
('صباغ','🎨','صبغ وديكور المنازل والمحلات',70),
('ميكانيكي سيارات','🚗','صيانة وإصلاح السيارات',80)
on conflict(name) do nothing;

-- 3) Final shop courier functions
create or replace function public.update_shop_delivery_status(p_delivery_id bigint,p_status text,p_otp text default null)
returns void language plpgsql security definer set search_path=public as $$
declare d public.shop_order_deliveries%rowtype;
begin
  if not public.has_approved_role('delivery_driver') then raise exception 'غير مصرح كمندوب'; end if;
  select * into d from public.shop_order_deliveries where id=p_delivery_id and driver_id=auth.uid() for update;
  if not found then raise exception 'التوصيل غير موجود'; end if;
  if p_status='picked_up' and d.status<>'accepted' then raise exception 'يجب قبول الطلب أولاً'; end if;
  if p_status='on_the_way' and d.status<>'picked_up' then raise exception 'يجب تسجيل الاستلام أولاً'; end if;
  if p_status='delivered' then
    if d.status<>'on_the_way' then raise exception 'يجب أن يكون الطلب بالطريق أولاً'; end if;
    if trim(coalesce(p_otp,''))<>d.otp_code then raise exception 'رمز التسليم غير صحيح'; end if;
  end if;
  if p_status not in('picked_up','on_the_way','delivered') then raise exception 'حالة غير صحيحة'; end if;
  update public.shop_order_deliveries set status=p_status,
    picked_up_at=case when p_status='picked_up' then now() else picked_up_at end,
    delivered_at=case when p_status='delivered' then now() else delivered_at end,
    updated_at=now() where id=p_delivery_id;
  if p_status in('picked_up','on_the_way') then
    update public.shop_orders set status='out_for_delivery',updated_at=now() where id=d.order_id and status<>'cancelled';
  elsif p_status='delivered' then
    if not exists(select 1 from public.shop_order_deliveries x where x.order_id=d.order_id and x.status not in('delivered','cancelled')) then
      update public.shop_orders set status='completed',updated_at=now() where id=d.order_id and status<>'cancelled';
    end if;
  end if;
end$$;
grant execute on function public.update_shop_delivery_status(bigint,text,text) to authenticated;

create or replace function public.get_my_shop_deliveries()
returns jsonb language sql stable security definer set search_path=public as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',d.id,'order_id',d.order_id,'status',d.status,'pickup_name',d.pickup_name,'otp_code',
      case when d.status in('picked_up','on_the_way') then d.otp_code else null end,
    'driver_id',d.driver_id,
    'driver_name',to_jsonb(tp)->>'full_name',
    'driver_phone',to_jsonb(tp)->>'phone',
    'vehicle_type',to_jsonb(tp)->>'vehicle_type',
    'vehicle_model',to_jsonb(tp)->>'vehicle_model',
    'vehicle_color',to_jsonb(tp)->>'vehicle_color',
    'plate_number',to_jsonb(tp)->>'plate_number',
    'accepted_at',d.accepted_at,'picked_up_at',d.picked_up_at,'delivered_at',d.delivered_at
  ) order by d.created_at desc),'[]'::jsonb)
  from public.shop_order_deliveries d
  left join public.transport_profiles tp on tp.user_id=d.driver_id
  where d.customer_id=auth.uid();
$$;
grant execute on function public.get_my_shop_deliveries() to authenticated;

-- 4) Account deletion request foundation for Google Play
create table if not exists public.account_deletion_requests(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 reason text,
 status text not null default 'requested' check(status in('requested','processing','completed','cancelled')),
 requested_at timestamptz not null default now(),
 completed_at timestamptz,
 unique(user_id,status)
);
alter table public.account_deletion_requests enable row level security;
drop policy if exists "users read own deletion request" on public.account_deletion_requests;
create policy "users read own deletion request" on public.account_deletion_requests for select to authenticated using(user_id=auth.uid());
drop policy if exists "users create own deletion request" on public.account_deletion_requests;
create policy "users create own deletion request" on public.account_deletion_requests for insert to authenticated with check(user_id=auth.uid());
grant select,insert on public.account_deletion_requests to authenticated;

create or replace function public.request_account_deletion(p_reason text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول أولاً'; end if;
  select id into v_id from public.account_deletion_requests
  where user_id=auth.uid() and status in('requested','processing')
  order by requested_at desc limit 1;
  if v_id is not null then return v_id; end if;
  insert into public.account_deletion_requests(user_id,reason)
  values(auth.uid(),nullif(trim(coalesce(p_reason,'')),'')) returning id into v_id;
  return v_id;
end$$;
grant execute on function public.request_account_deletion(text) to authenticated;

select 'HA Marketing remaining install completed' as result;
