-- HA Marketing - New Features Batch 2026-09-04
-- WhatsApp OTP intentionally NOT included in this batch.

-- Personal profile fields
alter table public.profiles add column if not exists birth_date date;
alter table public.profiles add column if not exists gender text;
alter table public.profiles add column if not exists occupation text;
alter table public.profiles add column if not exists employer text;
alter table public.profiles add column if not exists height_cm numeric(6,2);
alter table public.profiles add column if not exists weight_kg numeric(6,2);
alter table public.profiles add column if not exists blood_type text;
alter table public.profiles add column if not exists emergency_phone text;
alter table public.profiles add column if not exists personal_notes text;
alter table public.profiles add column if not exists monthly_income numeric(14,2);
alter table public.profiles add column if not exists monthly_expenses numeric(14,2);
alter table public.profiles add column if not exists bank_name text;
alter table public.profiles add column if not exists finance_ref text;
alter table public.profiles add column if not exists finance_notes text;

-- Student grades
create table if not exists public.student_grades(
 id bigint generated by default as identity primary key,
 owner_user_id uuid not null references auth.users(id) on delete cascade,
 student_id bigint not null references public.study_students(id) on delete cascade,
 subject text not null, term text,
 daily numeric(5,2) default 0, monthly numeric(5,2) default 0,
 dictation numeric(5,2) default 0, participation numeric(5,2) default 0,
 effort numeric(5,2) default 0, exam numeric(5,2) default 0,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.student_grades enable row level security;
drop policy if exists "grades own" on public.student_grades;
create policy "grades own" on public.student_grades for all to authenticated
using(owner_user_id=auth.uid() or public.is_super_admin())
with check(owner_user_id=auth.uid() or public.is_super_admin());
grant select,insert,update,delete on public.student_grades to authenticated;

-- Student talents
create table if not exists public.student_talents(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 student_id bigint references public.study_students(id) on delete set null,
 title text not null, talent_type text not null, details text, image_url text,
 is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.student_talents enable row level security;
drop policy if exists "talents public read" on public.student_talents;
create policy "talents public read" on public.student_talents for select to anon,authenticated using(is_active=true or user_id=auth.uid() or public.is_super_admin());
drop policy if exists "talents own insert" on public.student_talents;
create policy "talents own insert" on public.student_talents for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "talents own change" on public.student_talents;
create policy "talents own change" on public.student_talents for update to authenticated using(user_id=auth.uid() or public.is_super_admin()) with check(user_id=auth.uid() or public.is_super_admin());
drop policy if exists "talents own delete" on public.student_talents;
create policy "talents own delete" on public.student_talents for delete to authenticated using(user_id=auth.uid() or public.is_super_admin());
grant select on public.student_talents to anon;
grant select,insert,update,delete on public.student_talents to authenticated;
insert into storage.buckets(id,name,public) values('student-talents','student-talents',true) on conflict(id) do update set public=true;
drop policy if exists "student talents public storage" on storage.objects;
create policy "student talents public storage" on storage.objects for select to public using(bucket_id='student-talents');
drop policy if exists "student talents upload" on storage.objects;
create policy "student talents upload" on storage.objects for insert to authenticated with check(bucket_id='student-talents');
drop policy if exists "student talents delete own" on storage.objects;
create policy "student talents delete own" on storage.objects for delete to authenticated using(bucket_id='student-talents' and owner_id=auth.uid()::text);

-- Student transport routes: only approved delivery driver or super admin can create/manage
create table if not exists public.student_transport_routes(
 id bigint generated by default as identity primary key,
 owner_user_id uuid not null references auth.users(id) on delete cascade,
 driver_name text not null, phone text not null, vehicle_type text not null default 'باص', plate_number text,
 from_area text not null, to_institution text not null, seats integer not null check(seats>0), available_seats integer not null default 0,
 pickup_time time, return_time time, monthly_price numeric(12,2) not null default 0, days text, notes text,
 is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.student_transport_routes enable row level security;
drop policy if exists "student routes public read" on public.student_transport_routes;
create policy "student routes public read" on public.student_transport_routes for select to anon,authenticated using(is_active=true or owner_user_id=auth.uid() or public.is_super_admin());
drop policy if exists "student routes transport insert" on public.student_transport_routes;
create policy "student routes transport insert" on public.student_transport_routes for insert to authenticated with check(owner_user_id=auth.uid() and (public.has_approved_role('delivery_driver') or public.is_super_admin()));
drop policy if exists "student routes transport update" on public.student_transport_routes;
create policy "student routes transport update" on public.student_transport_routes for update to authenticated using((owner_user_id=auth.uid() and public.has_approved_role('delivery_driver')) or public.is_super_admin()) with check((owner_user_id=auth.uid() and public.has_approved_role('delivery_driver')) or public.is_super_admin());
drop policy if exists "student routes transport delete" on public.student_transport_routes;
create policy "student routes transport delete" on public.student_transport_routes for delete to authenticated using((owner_user_id=auth.uid() and public.has_approved_role('delivery_driver')) or public.is_super_admin());
grant select on public.student_transport_routes to anon;
grant select,insert,update,delete on public.student_transport_routes to authenticated;

-- Sports manager helper
create or replace function public.can_manage_sports() returns boolean language sql stable security definer set search_path=public as $$
 select public.is_super_admin()
 or public.has_approved_role('service_provider')
 or exists(select 1 from public.profiles p where p.id=auth.uid() and p.account_type='employee' and coalesce(p.employee_status,'')='approved');
$$;
grant execute on function public.can_manage_sports() to authenticated;

create table if not exists public.sports_facilities(
 id bigint generated by default as identity primary key, owner_user_id uuid not null references auth.users(id) on delete cascade,
 facility_type text not null check(facility_type in ('stadium','gym')), name text not null, governorate text, address text not null,
 working_hours text, price numeric(12,2) default 0, phone text, details text, available_slots text,
 is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.sports_bookings(
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 facility_id bigint not null references public.sports_facilities(id) on delete cascade, booking_date date, booking_time time, notes text,
 status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled','completed')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists sports_booking_slot_unique on public.sports_bookings(facility_id,booking_date,booking_time) where booking_date is not null and booking_time is not null and status in ('pending','approved');
create table if not exists public.sports_teams(
 id bigint generated by default as identity primary key, owner_user_id uuid not null references auth.users(id) on delete cascade,
 name text not null, logo_url text, city text, details text, is_active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.sports_team_members(
 id bigint generated by default as identity primary key, team_id bigint not null references public.sports_teams(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade, position text, shirt_number integer, notes text,
 created_at timestamptz not null default now(), unique(team_id,user_id)
);
create table if not exists public.sports_leagues(
 id bigint generated by default as identity primary key, owner_user_id uuid references auth.users(id) on delete set null,
 name text not null, governorate text, start_date date, end_date date, details text, is_active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.sports_facilities enable row level security; alter table public.sports_bookings enable row level security; alter table public.sports_teams enable row level security; alter table public.sports_team_members enable row level security; alter table public.sports_leagues enable row level security;
drop policy if exists "sports facilities read" on public.sports_facilities; create policy "sports facilities read" on public.sports_facilities for select to anon,authenticated using(is_active=true or owner_user_id=auth.uid() or public.is_super_admin());
drop policy if exists "sports facilities manage" on public.sports_facilities; create policy "sports facilities manage" on public.sports_facilities for all to authenticated using((owner_user_id=auth.uid() and public.can_manage_sports()) or public.is_super_admin()) with check((owner_user_id=auth.uid() and public.can_manage_sports()) or public.is_super_admin());
drop policy if exists "sports bookings own read" on public.sports_bookings; create policy "sports bookings own read" on public.sports_bookings for select to authenticated using(user_id=auth.uid() or public.is_super_admin() or exists(select 1 from public.sports_facilities f where f.id=facility_id and f.owner_user_id=auth.uid()));
drop policy if exists "sports bookings own insert" on public.sports_bookings; create policy "sports bookings own insert" on public.sports_bookings for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "sports bookings update" on public.sports_bookings; create policy "sports bookings update" on public.sports_bookings for update to authenticated using(user_id=auth.uid() or public.is_super_admin() or exists(select 1 from public.sports_facilities f where f.id=facility_id and f.owner_user_id=auth.uid())) with check(user_id=auth.uid() or public.is_super_admin() or exists(select 1 from public.sports_facilities f where f.id=facility_id and f.owner_user_id=auth.uid()));
drop policy if exists "sports teams read" on public.sports_teams; create policy "sports teams read" on public.sports_teams for select to anon,authenticated using(is_active=true or owner_user_id=auth.uid() or public.is_super_admin());
drop policy if exists "sports teams own" on public.sports_teams; create policy "sports teams own" on public.sports_teams for all to authenticated using(owner_user_id=auth.uid() or public.is_super_admin()) with check(owner_user_id=auth.uid() or public.is_super_admin());
drop policy if exists "sports members read" on public.sports_team_members; create policy "sports members read" on public.sports_team_members for select to anon,authenticated using(true);
drop policy if exists "sports members team owner" on public.sports_team_members; create policy "sports members team owner" on public.sports_team_members for all to authenticated using(public.is_super_admin() or exists(select 1 from public.sports_teams t where t.id=team_id and t.owner_user_id=auth.uid())) with check(public.is_super_admin() or exists(select 1 from public.sports_teams t where t.id=team_id and t.owner_user_id=auth.uid()));
drop policy if exists "sports leagues read" on public.sports_leagues; create policy "sports leagues read" on public.sports_leagues for select to anon,authenticated using(is_active=true or owner_user_id=auth.uid() or public.is_super_admin());
drop policy if exists "sports leagues manage" on public.sports_leagues; create policy "sports leagues manage" on public.sports_leagues for all to authenticated using(public.can_manage_sports() or public.is_super_admin()) with check(public.can_manage_sports() or public.is_super_admin());
grant select on public.sports_facilities,public.sports_teams,public.sports_team_members,public.sports_leagues to anon;
grant select,insert,update,delete on public.sports_facilities,public.sports_bookings,public.sports_teams,public.sports_team_members,public.sports_leagues to authenticated;

-- Store accounting
create table if not exists public.shop_accounting_entries(
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 business_id bigint references public.shop_businesses(id) on delete set null,
 entry_type text not null check(entry_type in ('income','expense','receivable','payable')),
 category text, description text, amount numeric(14,2) not null check(amount>=0), entry_date date not null default current_date,
 party_name text, reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.shop_accounting_parties(
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 party_type text not null check(party_type in ('customer','supplier')), name text not null, phone text, notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.shop_accounting_entries enable row level security; alter table public.shop_accounting_parties enable row level security;
drop policy if exists "accounting entries seller" on public.shop_accounting_entries; create policy "accounting entries seller" on public.shop_accounting_entries for all to authenticated using((user_id=auth.uid() and public.has_approved_role('seller')) or public.is_super_admin()) with check((user_id=auth.uid() and public.has_approved_role('seller')) or public.is_super_admin());
drop policy if exists "accounting parties seller" on public.shop_accounting_parties; create policy "accounting parties seller" on public.shop_accounting_parties for all to authenticated using((user_id=auth.uid() and public.has_approved_role('seller')) or public.is_super_admin()) with check((user_id=auth.uid() and public.has_approved_role('seller')) or public.is_super_admin());
grant select,insert,update,delete on public.shop_accounting_entries,public.shop_accounting_parties to authenticated;
