-- HA Marketing - Parent grades + study privacy
create extension if not exists pgcrypto;

alter table public.study_students add column if not exists parent_access_code text;
create unique index if not exists study_students_parent_code_uq on public.study_students(parent_access_code) where parent_access_code is not null;

create table if not exists public.study_parent_links(
 id bigint generated by default as identity primary key,
 parent_user_id uuid not null references auth.users(id) on delete cascade,
 student_id bigint not null references public.study_students(id) on delete cascade,
 created_at timestamptz not null default now(),
 unique(parent_user_id,student_id)
);
alter table public.study_parent_links enable row level security;
drop policy if exists "parent reads own links" on public.study_parent_links;
create policy "parent reads own links" on public.study_parent_links for select to authenticated using(parent_user_id=auth.uid() or public.is_super_admin());
grant select on public.study_parent_links to authenticated;

create or replace function public.generate_student_parent_code(p_student_id bigint)
returns text language plpgsql security definer set search_path=public,extensions as $$
declare v_code text;
begin
 if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
 if not exists(select 1 from public.study_students where id=p_student_id and (owner_user_id=auth.uid() or public.is_super_admin())) then raise exception 'لا توجد صلاحية'; end if;
 v_code:=upper(substr(encode(gen_random_bytes(6),'hex'),1,8));
 update public.study_students set parent_access_code=v_code where id=p_student_id;
 return v_code;
end $$;


create or replace function public.link_parent_to_student(p_code text)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_student bigint;
begin
 if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
 select id into v_student from public.study_students where upper(parent_access_code)=upper(trim(p_code)) limit 1;
 if v_student is null then raise exception 'رمز الطالب غير صحيح'; end if;
 insert into public.study_parent_links(parent_user_id,student_id) values(auth.uid(),v_student) on conflict(parent_user_id,student_id) do nothing;
 return v_student;
end $$;

create or replace function public.get_my_parent_students()
returns jsonb language sql security definer set search_path=public as $$
 select coalesce(jsonb_agg(jsonb_build_object('student_id',s.id,'student_name',s.student_name,'education_level',s.education_level,'grade',s.grade,'institution_name',s.institution_name)),'[]'::jsonb)
 from public.study_parent_links l join public.study_students s on s.id=l.student_id where l.parent_user_id=auth.uid();
$$;

create or replace function public.get_parent_student_grades(p_student_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_result jsonb;
begin
 if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
 if not exists(select 1 from public.study_parent_links where parent_user_id=auth.uid() and student_id=p_student_id) and not public.is_super_admin() then raise exception 'لا توجد صلاحية لعرض درجات هذا الطالب'; end if;
 select coalesce(jsonb_agg(to_jsonb(g) order by g.created_at desc),'[]'::jsonb) into v_result from public.student_grades g where g.student_id=p_student_id;
 return v_result;
end $$;

grant execute on function public.generate_student_parent_code(bigint) to authenticated;
grant execute on function public.link_parent_to_student(text) to authenticated;
grant execute on function public.get_my_parent_students() to authenticated;
grant execute on function public.get_parent_student_grades(bigint) to authenticated;
