-- HA Marketing - Personal Finance + Daily Calendar

create table if not exists public.personal_finance_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  account_name text not null default 'حسابي الشخصي',
  opening_balance numeric(18,3) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.personal_finance_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('income','expense')),
  amount numeric(18,3) not null check (amount > 0),
  transaction_date date not null default current_date,
  category text,
  title text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists personal_finance_transactions_user_date_idx
  on public.personal_finance_transactions(user_id, transaction_date desc);

alter table public.personal_finance_accounts enable row level security;
alter table public.personal_finance_transactions enable row level security;

drop policy if exists "users manage own finance account" on public.personal_finance_accounts;
create policy "users manage own finance account" on public.personal_finance_accounts
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "users manage own finance transactions" on public.personal_finance_transactions;
create policy "users manage own finance transactions" on public.personal_finance_transactions
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select, insert, update, delete on public.personal_finance_accounts to authenticated;
grant select, insert, update, delete on public.personal_finance_transactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
