-- HA Marketing - Firebase Web Push final database wiring
-- Run once in Supabase SQL Editor. Safe to re-run.

create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  platform text not null default 'web',
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_tokens_user_id_idx on public.push_tokens(user_id);

alter table public.push_tokens enable row level security;

drop policy if exists "users read own push tokens" on public.push_tokens;
create policy "users read own push tokens"
on public.push_tokens for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "users insert own push tokens" on public.push_tokens;
create policy "users insert own push tokens"
on public.push_tokens for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users update own push tokens" on public.push_tokens;
create policy "users update own push tokens"
on public.push_tokens for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users delete own push tokens" on public.push_tokens;
create policy "users delete own push tokens"
on public.push_tokens for delete to authenticated
using (auth.uid() = user_id);

alter table public.notifications add column if not exists push_sent_at timestamptz;
alter table public.notifications add column if not exists push_attempted_at timestamptz;
alter table public.notifications add column if not exists push_error text;

create extension if not exists pg_net with schema extensions;

-- Every legitimate in-app notification is handed to the Edge Function.
-- The Edge Function itself loads recipient + message from the database,
-- so callers cannot choose an arbitrary user/message.
create or replace function public.dispatch_notification_push()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform net.http_post(
    url := 'https://ubayrhtshgtgggxprrek.supabase.co/functions/v1/send-fcm-push',
    headers := jsonb_build_object('Content-Type','application/json'),
    body := jsonb_build_object('notification_id', new.id),
    timeout_milliseconds := 10000
  );
  return new;
exception
  when others then
    -- Never block creation of an in-app notification if push delivery is temporarily unavailable.
    return new;
end;
$$;

drop trigger if exists trg_dispatch_notification_push on public.notifications;
create trigger trg_dispatch_notification_push
after insert on public.notifications
for each row execute function public.dispatch_notification_push();
