-- HA Marketing - Real Service Orders setup
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references auth.users(id) on delete cascade,
  department text not null default 'services',
  order_type text not null,
  description text,
  phone text,
  area text,
  customer_lat double precision,
  customer_lng double precision,
  employee_lat double precision,
  employee_lng double precision,
  attachment_url text,
  status text not null default 'new',
  assigned_employee_id uuid references auth.users(id) on delete set null,
  cancel_reason text,
  customer_rating int check (customer_rating between 1 and 5),
  employee_rating int check (employee_rating between 1 and 5),
  customer_review text,
  employee_review text,
  accepted_at timestamptz,
  on_the_way_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists customer_id uuid references auth.users(id) on delete cascade;
alter table public.orders add column if not exists department text default 'services';
alter table public.orders add column if not exists order_type text;
alter table public.orders add column if not exists description text;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists area text;
alter table public.orders add column if not exists customer_lat double precision;
alter table public.orders add column if not exists customer_lng double precision;
alter table public.orders add column if not exists employee_lat double precision;
alter table public.orders add column if not exists employee_lng double precision;
alter table public.orders add column if not exists attachment_url text;
alter table public.orders add column if not exists status text default 'new';
alter table public.orders add column if not exists assigned_employee_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists cancel_reason text;
alter table public.orders add column if not exists customer_rating int;
alter table public.orders add column if not exists employee_rating int;
alter table public.orders add column if not exists customer_review text;
alter table public.orders add column if not exists employee_review text;
alter table public.orders add column if not exists accepted_at timestamptz;
alter table public.orders add column if not exists on_the_way_at timestamptz;
alter table public.orders add column if not exists completed_at timestamptz;
alter table public.orders add column if not exists cancelled_at timestamptz;
alter table public.orders add column if not exists created_at timestamptz default now();
alter table public.orders add column if not exists updated_at timestamptz default now();

-- ensure a services employee role exists
insert into public.employee_roles(role_key, role_name, department, is_active)
values ('services','موظف خدمات','services',true)
on conflict (role_key) do update set role_name=excluded.role_name, department=excluded.department, is_active=true;

-- existing customer-service employees are also routed to service requests
update public.employee_roles set department='services' where role_key='customer_service';

alter table public.orders enable row level security;

drop policy if exists "customers insert own orders" on public.orders;
create policy "customers insert own orders" on public.orders for insert to authenticated
with check (
  auth.uid() = customer_id
  and exists(select 1 from public.profiles p where p.id=auth.uid() and p.account_type='customer')
);

drop policy if exists "customers read own orders" on public.orders;
create policy "customers read own orders" on public.orders for select to authenticated
using (auth.uid() = customer_id);

drop policy if exists "employees read matching service orders" on public.orders;
create policy "employees read matching service orders" on public.orders for select to authenticated
using (
  exists (
    select 1 from public.profiles p
    join public.employee_roles r on r.id=p.employee_role_id
    where p.id=auth.uid() and p.account_type='employee' and p.employee_status='approved'
      and r.is_active=true and r.department=orders.department
      and (orders.assigned_employee_id is null or orders.assigned_employee_id=auth.uid())
  )
);

create or replace function public.customer_cancel_order(p_order_id bigint, p_reason text)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.orders set status='cancelled', cancel_reason=nullif(trim(p_reason),''), cancelled_at=now(), updated_at=now()
  where id=p_order_id and customer_id=auth.uid() and status in ('new','accepted');
  if not found then raise exception 'Order cannot be cancelled'; end if;
end; $$;
grant execute on function public.customer_cancel_order(bigint,text) to authenticated;

create or replace function public.employee_update_order(p_order_id bigint, p_status text, p_assign_to_me boolean default false)
returns void language plpgsql security definer set search_path=public as $$
declare v_dept text; v_assigned uuid; v_current text;
begin
  select department,assigned_employee_id,status into v_dept,v_assigned,v_current from public.orders where id=p_order_id for update;
  if not found then raise exception 'Order not found'; end if;
  if not exists(select 1 from public.profiles p join public.employee_roles r on r.id=p.employee_role_id
    where p.id=auth.uid() and p.account_type='employee' and p.employee_status='approved' and r.is_active=true and r.department=v_dept)
  then raise exception 'Not allowed'; end if;

  if p_status='accepted' then
    if v_assigned is not null and v_assigned<>auth.uid() then raise exception 'Order already assigned'; end if;
    update public.orders set assigned_employee_id=auth.uid(),status='accepted',accepted_at=coalesce(accepted_at,now()),updated_at=now() where id=p_order_id;
  elsif p_status='on_the_way' then
    if v_assigned<>auth.uid() or v_current<>'accepted' then raise exception 'Invalid status change'; end if;
    update public.orders set status='on_the_way',on_the_way_at=now(),updated_at=now() where id=p_order_id;
  elsif p_status='completed' then
    if v_assigned<>auth.uid() or v_current<>'on_the_way' then raise exception 'Invalid status change'; end if;
    update public.orders set status='completed',completed_at=now(),updated_at=now() where id=p_order_id;
  elsif p_status='cancelled' then
    if v_assigned<>auth.uid() or v_current not in ('accepted','on_the_way') then raise exception 'Invalid status change'; end if;
    update public.orders set status='cancelled',cancelled_at=now(),updated_at=now() where id=p_order_id;
  else raise exception 'Invalid status'; end if;
end; $$;
grant execute on function public.employee_update_order(bigint,text,boolean) to authenticated;

create or replace function public.employee_update_location(p_order_id bigint,p_lat double precision,p_lng double precision)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.orders set employee_lat=p_lat,employee_lng=p_lng,updated_at=now()
  where id=p_order_id and assigned_employee_id=auth.uid() and status='on_the_way';
  if not found then raise exception 'Not allowed'; end if;
end; $$;
grant execute on function public.employee_update_location(bigint,double precision,double precision) to authenticated;

create or replace function public.customer_rate_order(p_order_id bigint,p_rating int,p_review text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_rating not between 1 and 5 then raise exception 'Rating must be 1-5'; end if;
  update public.orders set customer_rating=p_rating,customer_review=nullif(trim(p_review),''),updated_at=now()
  where id=p_order_id and customer_id=auth.uid() and status='completed';
  if not found then raise exception 'Not allowed'; end if;
end; $$;
grant execute on function public.customer_rate_order(bigint,int,text) to authenticated;

create or replace function public.employee_rate_order(p_order_id bigint,p_rating int,p_review text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_rating not between 1 and 5 then raise exception 'Rating must be 1-5'; end if;
  update public.orders set employee_rating=p_rating,employee_review=nullif(trim(p_review),''),updated_at=now()
  where id=p_order_id and assigned_employee_id=auth.uid() and status='completed';
  if not found then raise exception 'Not allowed'; end if;
end; $$;
grant execute on function public.employee_rate_order(bigint,int,text) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('service-attachments','service-attachments',true,20971520,array['image/jpeg','image/png','image/webp','video/mp4','video/webm'])
on conflict(id) do update set public=true,file_size_limit=20971520,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "service attachment uploads" on storage.objects;
create policy "service attachment uploads" on storage.objects for insert to authenticated
with check(bucket_id='service-attachments' and (storage.foldername(name))[1]=auth.uid()::text);

-- enable realtime for live status updates; duplicate add is safely ignored
do $$ begin
  alter publication supabase_realtime add table public.orders;
exception when duplicate_object then null; end $$;
