-- HA Marketing - Service Marketplace
create table if not exists public.service_categories(
 id bigint generated by default as identity primary key,
 name text not null unique,
 icon text default '🛠️',
 description text,
 image_url text,
 sort_order integer not null default 100,
 is_active boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists public.service_providers(
 id bigint generated by default as identity primary key,
 category_id bigint not null references public.service_categories(id) on delete cascade,
 name text not null,
 phone text,
 whatsapp text,
 address text,
 governorate text,
 area text,
 image_url text,
 description text,
 skills text,
 working_hours text,
 price_from numeric(12,2),
 price_note text,
 map_url text,
 lat double precision,
 lng double precision,
 is_available boolean not null default true,
 is_active boolean not null default true,
 is_verified boolean not null default false,
 sort_order integer not null default 100,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.service_requests(
 id bigint generated by default as identity primary key,
 customer_id uuid not null references auth.users(id) on delete cascade,
 provider_id bigint references public.service_providers(id) on delete set null,
 category_id bigint references public.service_categories(id) on delete set null,
 customer_name text not null,
 phone text not null,
 address text not null,
 details text not null,
 preferred_date date,
 preferred_time text,
 customer_lat double precision,
 customer_lng double precision,
 status text not null default 'new' check(status in('new','accepted','on_the_way','in_progress','completed','cancelled')),
 cancel_reason text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.service_favorites(
 user_id uuid not null references auth.users(id) on delete cascade,
 provider_id bigint not null references public.service_providers(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(user_id,provider_id)
);
create table if not exists public.service_reviews(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 provider_id bigint not null references public.service_providers(id) on delete cascade,
 rating integer not null check(rating between 1 and 5),
 comment text,
 created_at timestamptz not null default now(),
 unique(user_id,provider_id)
);
create index if not exists service_provider_category_idx on public.service_providers(category_id,is_active,sort_order);
create index if not exists service_request_customer_idx on public.service_requests(customer_id,created_at desc);

alter table public.service_categories enable row level security;
alter table public.service_providers enable row level security;
alter table public.service_requests enable row level security;
alter table public.service_favorites enable row level security;
alter table public.service_reviews enable row level security;

-- يعتمد على is_super_admin() الموجودة عندك مسبقاً
create or replace function public.is_app_admin()
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.app_admins a where a.user_id=auth.uid() and a.is_active=true);
$$;
grant execute on function public.is_app_admin() to authenticated;

-- قراءة عامة
 drop policy if exists "service categories public read" on public.service_categories;
create policy "service categories public read" on public.service_categories for select using(is_active=true or public.is_app_admin());
 drop policy if exists "service providers public read" on public.service_providers;
create policy "service providers public read" on public.service_providers for select using(is_active=true or public.is_app_admin());

-- إدارة الأدمن
 drop policy if exists "service categories admin manage" on public.service_categories;
create policy "service categories admin manage" on public.service_categories for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
 drop policy if exists "service providers admin manage" on public.service_providers;
create policy "service providers admin manage" on public.service_providers for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());

-- طلبات العميل + الأدمن
 drop policy if exists "service requests own read" on public.service_requests;
create policy "service requests own read" on public.service_requests for select to authenticated using(customer_id=auth.uid() or public.is_app_admin());
 drop policy if exists "service requests own insert" on public.service_requests;
create policy "service requests own insert" on public.service_requests for insert to authenticated with check(customer_id=auth.uid());
 drop policy if exists "service requests own update" on public.service_requests;
create policy "service requests own update" on public.service_requests for update to authenticated using(customer_id=auth.uid() or public.is_app_admin()) with check(customer_id=auth.uid() or public.is_app_admin());

-- مفضلة وتقييمات
 drop policy if exists "service favorites own" on public.service_favorites;
create policy "service favorites own" on public.service_favorites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
 drop policy if exists "service reviews public" on public.service_reviews;
create policy "service reviews public" on public.service_reviews for select using(true);
 drop policy if exists "service reviews own insert" on public.service_reviews;
create policy "service reviews own insert" on public.service_reviews for insert to authenticated with check(user_id=auth.uid());
 drop policy if exists "service reviews own update" on public.service_reviews;
create policy "service reviews own update" on public.service_reviews for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
 drop policy if exists "service reviews own delete" on public.service_reviews;
create policy "service reviews own delete" on public.service_reviews for delete to authenticated using(user_id=auth.uid() or public.is_app_admin());

grant select on public.service_categories,public.service_providers,public.service_reviews to anon,authenticated;
grant select,insert,update,delete on public.service_categories,public.service_providers,public.service_requests,public.service_favorites,public.service_reviews to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('service-images','service-images',true,6291456,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=true,file_size_limit=6291456,allowed_mime_types=excluded.allowed_mime_types;
 drop policy if exists "service images admin insert" on storage.objects;
create policy "service images admin insert" on storage.objects for insert to authenticated with check(bucket_id='service-images' and public.is_app_admin());
 drop policy if exists "service images admin update" on storage.objects;
create policy "service images admin update" on storage.objects for update to authenticated using(bucket_id='service-images' and public.is_app_admin());
 drop policy if exists "service images admin delete" on storage.objects;
create policy "service images admin delete" on storage.objects for delete to authenticated using(bucket_id='service-images' and public.is_app_admin());

insert into public.service_categories(name,icon,description,sort_order) values
('حداد','⚒️','أعمال الحدادة والأبواب والهياكل المعدنية',10),
('حلاق','💈','حلاقة وتجميل وعناية شخصية',20),
('كهربائي','⚡','تمديدات وصيانة كهربائية',30),
('سباك','🔧','صيانة وتمديدات صحية ومياه',40),
('نجار','🪚','أعمال النجارة والأثاث',50),
('تبريد وتكييف','❄️','صيانة وتركيب أجهزة التبريد والتكييف',60),
('صباغ','🎨','صبغ وديكور المنازل والمحلات',70),
('ميكانيكي سيارات','🚗','صيانة وإصلاح السيارات',80)
on conflict(name) do nothing;
