-- HA Marketing - Advanced Shop Update
-- Search/favorites/ratings/discounts/coupons/saved addresses/delivery/order receipt

alter table public.products add column if not exists discount_price bigint;
alter table public.products add column if not exists min_order_qty int not null default 1;
alter table public.products add column if not exists options_json jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists specifications text;

do $$ begin
  alter table public.products add constraint products_discount_price_check check(discount_price is null or discount_price>=0);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.products add constraint products_min_order_qty_check check(min_order_qty>=1);
exception when duplicate_object then null; end $$;

alter table public.shop_orders add column if not exists subtotal bigint not null default 0;
alter table public.shop_orders add column if not exists delivery_fee bigint not null default 0;
alter table public.shop_orders add column if not exists discount_amount bigint not null default 0;
alter table public.shop_orders add column if not exists coupon_code text;
alter table public.shop_orders add column if not exists cancel_reason text;

alter table public.shop_order_items add column if not exists option_text text;

create table if not exists public.shop_favorites(
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,product_id)
);

create table if not exists public.shop_product_reviews(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  rating int not null check(rating between 1 and 5),
  comment text,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,product_id)
);

create table if not exists public.shop_saved_addresses(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'العنوان',
  governorate text,
  address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.shop_coupons(
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check(discount_type in('percent','fixed')),
  discount_value bigint not null check(discount_value>=0),
  min_total bigint not null default 0,
  max_discount bigint,
  starts_at timestamptz,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.shop_delivery_fees(
  governorate text primary key,
  fee bigint not null default 0 check(fee>=0),
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.shop_favorites enable row level security;
alter table public.shop_product_reviews enable row level security;
alter table public.shop_saved_addresses enable row level security;
alter table public.shop_coupons enable row level security;
alter table public.shop_delivery_fees enable row level security;

drop policy if exists "favorites own" on public.shop_favorites;
create policy "favorites own" on public.shop_favorites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "reviews public read" on public.shop_product_reviews;
create policy "reviews public read" on public.shop_product_reviews for select using(is_visible=true or public.is_admin());
drop policy if exists "reviews own insert" on public.shop_product_reviews;
create policy "reviews own insert" on public.shop_product_reviews for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "reviews own update" on public.shop_product_reviews;
create policy "reviews own update" on public.shop_product_reviews for update to authenticated using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());

drop policy if exists "addresses own" on public.shop_saved_addresses;
create policy "addresses own" on public.shop_saved_addresses for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "coupons customer read" on public.shop_coupons;
create policy "coupons customer read" on public.shop_coupons for select to authenticated using(is_active=true);
drop policy if exists "coupons admin" on public.shop_coupons;
create policy "coupons admin" on public.shop_coupons for all to authenticated using(public.is_admin() or public.is_super_admin()) with check(public.is_admin() or public.is_super_admin());
drop policy if exists "delivery fees public" on public.shop_delivery_fees;
create policy "delivery fees public" on public.shop_delivery_fees for select using(is_active=true or public.is_admin());
drop policy if exists "delivery fees admin" on public.shop_delivery_fees;
create policy "delivery fees admin" on public.shop_delivery_fees for all to authenticated using(public.is_admin()) with check(public.is_admin());

grant select,insert,update,delete on public.shop_favorites to authenticated;
grant select,insert,update on public.shop_product_reviews to authenticated;
grant select,insert,update,delete on public.shop_saved_addresses to authenticated;
grant select,insert,update,delete on public.shop_coupons to authenticated;
grant select,insert,update,delete on public.shop_delivery_fees to authenticated;
grant select on public.shop_product_reviews,public.shop_delivery_fees to anon;

create or replace function public.create_shop_order_v3(
  p_customer_name text,
  p_phone text,
  p_governorate text,
  p_address text,
  p_notes text,
  p_items jsonb,
  p_payment_method text default 'cash_on_delivery',
  p_coupon_code text default null
) returns bigint
language plpgsql security definer set search_path=public as $$
declare
  v_order bigint; v_item jsonb; v_product public.products%rowtype; v_qty int;
  v_subtotal bigint:=0; v_delivery bigint:=0; v_discount bigint:=0; v_total bigint:=0;
  v_method text; v_coupon public.shop_coupons%rowtype; v_price bigint; v_option text;
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  if coalesce(trim(p_customer_name),'')='' or coalesce(trim(p_phone),'')='' or coalesce(trim(p_address),'')='' then raise exception 'Customer name, phone and address are required'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty'; end if;
  v_method:=case when p_payment_method='electronic' then 'electronic' else 'cash_on_delivery' end;

  select fee into v_delivery from public.shop_delivery_fees where governorate=trim(coalesce(p_governorate,'')) and is_active=true;
  v_delivery:=coalesce(v_delivery,0);

  insert into public.shop_orders(customer_id,customer_name,phone,governorate,address,notes,payment_method,payment_status,delivery_fee)
  values(auth.uid(),trim(p_customer_name),trim(p_phone),nullif(trim(p_governorate),''),trim(p_address),nullif(trim(p_notes),''),v_method,'pending',v_delivery)
  returning id into v_order;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,coalesce((v_item->>'quantity')::int,1));
    v_option:=nullif(trim(coalesce(v_item->>'option_text','')),'');
    select * into v_product from public.products where id=(v_item->>'product_id')::bigint and is_active=true for update;
    if not found then raise exception 'Product unavailable'; end if;
    if v_qty < coalesce(v_product.min_order_qty,1) then raise exception 'Minimum quantity for % is %',v_product.name,v_product.min_order_qty; end if;
    if v_product.stock<v_qty then raise exception 'Insufficient stock for %',v_product.name; end if;
    v_price:=coalesce(v_product.discount_price,v_product.price);
    if v_price<0 then v_price:=v_product.price; end if;
    update public.products set stock=stock-v_qty,updated_at=now() where id=v_product.id;
    insert into public.shop_order_items(order_id,product_id,product_name,quantity,unit_price,subtotal,option_text)
    values(v_order,v_product.id,v_product.name,v_qty,v_price,v_price*v_qty,v_option);
    v_subtotal:=v_subtotal+(v_price*v_qty);
  end loop;

  if nullif(trim(coalesce(p_coupon_code,'')),'') is not null then
    select * into v_coupon from public.shop_coupons
    where upper(code)=upper(trim(p_coupon_code)) and is_active=true
      and (starts_at is null or starts_at<=now()) and (expires_at is null or expires_at>=now())
    limit 1;
    if found and v_subtotal>=v_coupon.min_total then
      if v_coupon.discount_type='percent' then
        v_discount:=floor(v_subtotal * least(v_coupon.discount_value,100)::numeric / 100);
      else
        v_discount:=v_coupon.discount_value;
      end if;
      if v_coupon.max_discount is not null then v_discount:=least(v_discount,v_coupon.max_discount); end if;
      v_discount:=least(v_discount,v_subtotal);
    end if;
  end if;

  v_total:=greatest(0,v_subtotal+v_delivery-v_discount);
  update public.shop_orders set subtotal=v_subtotal,delivery_fee=v_delivery,discount_amount=v_discount,
    coupon_code=case when v_discount>0 then upper(trim(p_coupon_code)) else null end,
    total=v_total,updated_at=now() where id=v_order;
  return v_order;
end$$;

grant execute on function public.create_shop_order_v3(text,text,text,text,text,jsonb,text,text) to authenticated;

create or replace function public.cancel_shop_order(p_order_id bigint,p_reason text default null) returns void
language plpgsql security definer set search_path=public as $$
declare r record;
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  if not exists(select 1 from public.shop_orders where id=p_order_id and customer_id=auth.uid() and status in('new','confirmed')) then raise exception 'Order cannot be cancelled'; end if;
  for r in select product_id,quantity from public.shop_order_items where order_id=p_order_id loop
    if r.product_id is not null then update public.products set stock=stock+r.quantity,updated_at=now() where id=r.product_id; end if;
  end loop;
  update public.shop_orders set status='cancelled',cancel_reason=nullif(trim(coalesce(p_reason,'')),''),updated_at=now() where id=p_order_id;
end$$;
grant execute on function public.cancel_shop_order(bigint,text) to authenticated;

-- Ensure principal/super admin can manage products and categories too
drop policy if exists "shop products admin all" on public.products;
create policy "shop products admin all" on public.products for all to authenticated using(public.is_admin() or public.is_super_admin()) with check(public.is_admin() or public.is_super_admin());
drop policy if exists "shop categories admin all" on public.product_categories;
create policy "shop categories admin all" on public.product_categories for all to authenticated using(public.is_admin() or public.is_super_admin()) with check(public.is_admin() or public.is_super_admin());
