-- HA Marketing - per-box Shop Now permissions + business/store cards
-- Run this ONCE in Supabase SQL Editor after the existing admin/account SQL.

create table if not exists public.shop_admin_permissions(
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  section_key text not null,
  can_manage boolean not null default true,
  created_at timestamptz not null default now(),
  primary key(admin_user_id,section_key)
);

create table if not exists public.shop_businesses(
  id bigint generated by default as identity primary key,
  section_key text not null,
  name text not null,
  location_text text not null,
  image_url text,
  description text,
  map_url text,
  page_url text,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_businesses_section_check check(section_key=any(array[
    'library','building_materials','cards_credit','yugioh','markets','restaurants','flowers',
    'home_appliances','printers','devices','device_accessories','clothes','shoes'
  ]))
);
create index if not exists shop_businesses_section_idx on public.shop_businesses(section_key,is_active,sort_order);

create or replace function public.can_manage_shop_section(p_section text)
returns boolean language sql stable security definer set search_path=public as $$
  select public.is_super_admin() or exists(
    select 1 from public.app_admins a
    join public.shop_admin_permissions p on p.admin_user_id=a.user_id
    where a.user_id=auth.uid() and a.is_active=true and p.section_key=p_section and p.can_manage=true
  );
$$;
grant execute on function public.can_manage_shop_section(text) to authenticated,anon;

alter table public.shop_admin_permissions enable row level security;
alter table public.shop_businesses enable row level security;

drop policy if exists "shop permissions super read" on public.shop_admin_permissions;
create policy "shop permissions super read" on public.shop_admin_permissions for select to authenticated
using(public.is_super_admin() or admin_user_id=auth.uid());

drop policy if exists "shop businesses public read" on public.shop_businesses;
create policy "shop businesses public read" on public.shop_businesses for select
using(is_active=true or public.can_manage_shop_section(section_key));

drop policy if exists "shop businesses scoped insert" on public.shop_businesses;
create policy "shop businesses scoped insert" on public.shop_businesses for insert to authenticated
with check(public.can_manage_shop_section(section_key) and created_by=auth.uid());

drop policy if exists "shop businesses scoped update" on public.shop_businesses;
create policy "shop businesses scoped update" on public.shop_businesses for update to authenticated
using(public.can_manage_shop_section(section_key)) with check(public.can_manage_shop_section(section_key));

drop policy if exists "shop businesses scoped delete" on public.shop_businesses;
create policy "shop businesses scoped delete" on public.shop_businesses for delete to authenticated
using(public.can_manage_shop_section(section_key));

create or replace function public.admin_set_shop_permissions(p_identifier text,p_sections text[] default '{}'::text[])
returns void language plpgsql security definer set search_path=public as $$
declare
  v_user uuid; v_id text:=trim(coalesce(p_identifier,'')); v_phone text:=regexp_replace(v_id,'[^0-9]','','g'); v_section text;
  allowed constant text[]:=array['library','building_materials','cards_credit','yugioh','markets','restaurants','flowers','home_appliances','printers','devices','device_accessories','clothes','shoes'];
begin
  if not public.is_super_admin() then raise exception 'Super Admin only'; end if;
  if v_phone ~ '^07[0-9]{9}$' then v_phone:='964'||substr(v_phone,2); end if;
  select id into v_user from public.profiles where username=v_id or phone=v_phone limit 1;
  if v_user is null then raise exception 'User profile not found'; end if;
  foreach v_section in array coalesce(p_sections,'{}'::text[]) loop
    if not(v_section=any(allowed)) then raise exception 'Invalid shop section: %',v_section; end if;
  end loop;
  delete from public.shop_admin_permissions where admin_user_id=v_user;
  insert into public.shop_admin_permissions(admin_user_id,section_key,can_manage)
    select v_user,x,true from unnest(coalesce(p_sections,'{}'::text[])) x;
end;$$;
grant execute on function public.admin_set_shop_permissions(text,text[]) to authenticated;

-- Public image bucket for shop cards.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('shop-images','shop-images',true,6291456,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=true,file_size_limit=6291456,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "shop images scoped insert" on storage.objects;
create policy "shop images scoped insert" on storage.objects for insert to authenticated
with check(bucket_id='shop-images' and public.can_manage_shop_section((storage.foldername(name))[1]));

drop policy if exists "shop images scoped update" on storage.objects;
create policy "shop images scoped update" on storage.objects for update to authenticated
using(bucket_id='shop-images' and public.can_manage_shop_section((storage.foldername(name))[1]));

drop policy if exists "shop images scoped delete" on storage.objects;
create policy "shop images scoped delete" on storage.objects for delete to authenticated
using(bucket_id='shop-images' and public.can_manage_shop_section((storage.foldername(name))[1]));
