-- HA Marketing - current shop schema used by store.html/cart.html/admin-shop.html
-- Reference/deploy script for a fresh Supabase project. The live project already has these objects.

create table if not exists public.product_categories(
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products(
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.product_categories(id) on delete restrict,
  name text not null,
  description text,
  price bigint not null check(price>=0),
  stock int not null default 0 check(stock>=0),
  image_url text,
  sku text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_orders(
  id bigint generated by default as identity primary key,
  customer_id uuid not null references auth.users(id) on delete restrict,
  customer_name text not null,
  phone text not null,
  governorate text,
  address text not null,
  notes text,
  payment_method text not null default 'cash_on_delivery',
  status text not null default 'new' check(status in('new','confirmed','preparing','out_for_delivery','completed','cancelled')),
  total bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_order_items(
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.shop_orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity int not null check(quantity>0),
  unit_price bigint not null check(unit_price>=0),
  subtotal bigint not null check(subtotal>=0)
);

alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.shop_orders enable row level security;
alter table public.shop_order_items enable row level security;

drop policy if exists "shop categories public read" on public.product_categories;
create policy "shop categories public read" on public.product_categories for select using(is_active=true or public.is_admin());
drop policy if exists "shop products public read" on public.products;
create policy "shop products public read" on public.products for select using(is_active=true or public.is_admin());
drop policy if exists "shop categories admin all" on public.product_categories;
create policy "shop categories admin all" on public.product_categories for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "shop products admin all" on public.products;
create policy "shop products admin all" on public.products for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "shop orders own read" on public.shop_orders;
create policy "shop orders own read" on public.shop_orders for select using(customer_id=auth.uid() or public.is_admin());
drop policy if exists "shop order items own read" on public.shop_order_items;
create policy "shop order items own read" on public.shop_order_items for select using(
  exists(select 1 from public.shop_orders o where o.id=order_id and (o.customer_id=auth.uid() or public.is_admin()))
);

create or replace function public.create_shop_order(
  p_customer_name text,
  p_phone text,
  p_governorate text,
  p_address text,
  p_notes text,
  p_items jsonb
) returns bigint
language plpgsql security definer set search_path=public as $$
declare
  v_order bigint; v_item jsonb; v_product public.products%rowtype; v_qty int; v_total bigint:=0;
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  if coalesce(trim(p_customer_name),'')='' or coalesce(trim(p_phone),'')='' or coalesce(trim(p_address),'')='' then
    raise exception 'Customer name, phone and address are required';
  end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty'; end if;

  insert into public.shop_orders(customer_id,customer_name,phone,governorate,address,notes)
  values(auth.uid(),trim(p_customer_name),trim(p_phone),nullif(trim(p_governorate),''),trim(p_address),nullif(trim(p_notes),''))
  returning id into v_order;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,coalesce((v_item->>'quantity')::int,1));
    select * into v_product from public.products
      where id=(v_item->>'product_id')::bigint and is_active=true for update;
    if not found then raise exception 'Product unavailable'; end if;
    if v_product.stock<v_qty then raise exception 'Insufficient stock for %',v_product.name; end if;
    update public.products set stock=stock-v_qty,updated_at=now() where id=v_product.id;
    insert into public.shop_order_items(order_id,product_id,product_name,quantity,unit_price,subtotal)
    values(v_order,v_product.id,v_product.name,v_qty,v_product.price,v_product.price*v_qty);
    v_total:=v_total+(v_product.price*v_qty);
  end loop;
  update public.shop_orders set total=v_total,updated_at=now() where id=v_order;
  return v_order;
end$$;
grant execute on function public.create_shop_order(text,text,text,text,text,jsonb) to authenticated;

create or replace function public.cancel_shop_order(p_order_id bigint) returns void
language plpgsql security definer set search_path=public as $$
declare r record;
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  if not exists(select 1 from public.shop_orders where id=p_order_id and customer_id=auth.uid() and status in('new','confirmed')) then
    raise exception 'Order cannot be cancelled';
  end if;
  for r in select product_id,quantity from public.shop_order_items where order_id=p_order_id loop
    if r.product_id is not null then update public.products set stock=stock+r.quantity,updated_at=now() where id=r.product_id; end if;
  end loop;
  update public.shop_orders set status='cancelled',updated_at=now() where id=p_order_id;
end$$;
grant execute on function public.cancel_shop_order(bigint) to authenticated;

create or replace function public.admin_update_shop_order_status(p_order_id bigint,p_status text) returns void
language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Admin only'; end if;
  if p_status not in('new','confirmed','preparing','out_for_delivery','completed','cancelled') then raise exception 'Invalid status'; end if;
  update public.shop_orders set status=p_status,updated_at=now() where id=p_order_id;
end$$;
grant execute on function public.admin_update_shop_order_status(bigint,text) to authenticated;
