-- HA Marketing - Student registration permissions
-- Chat session fix is in chat.html and needs no database change.

create table if not exists public.study_students(
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  student_name text not null,
  education_level text not null,
  grade text,
  institution_name text,
  governorate text,
  area text,
  phone text,
  birth_year integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists study_students_owner_idx on public.study_students(owner_user_id,created_at desc);
create index if not exists study_students_level_idx on public.study_students(education_level);

alter table public.study_students enable row level security;

drop policy if exists "students read own or super" on public.study_students;
create policy "students read own or super"
on public.study_students for select to authenticated
using(owner_user_id=auth.uid() or public.is_super_admin());

drop policy if exists "students insert own" on public.study_students;
create policy "students insert own"
on public.study_students for insert to authenticated
with check(owner_user_id=auth.uid());

drop policy if exists "students update own or super" on public.study_students;
create policy "students update own or super"
on public.study_students for update to authenticated
using(owner_user_id=auth.uid() or public.is_super_admin())
with check(owner_user_id=auth.uid() or public.is_super_admin());

drop policy if exists "students delete own or super" on public.study_students;
create policy "students delete own or super"
on public.study_students for delete to authenticated
using(owner_user_id=auth.uid() or public.is_super_admin());

grant select,insert,update,delete on public.study_students to authenticated;
