-- HA Marketing - Study advanced directory and admin management
create table if not exists public.study_directory(
 id bigint generated by default as identity primary key,
 type text not null,
 name text not null,
 governorate text,
 area text,
 address text,
 phone text,
 image_url text,
 map_url text,
 description text,
 sort_order integer not null default 100,
 is_active boolean not null default true,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists study_directory_active_idx on public.study_directory(is_active,sort_order);
alter table public.study_directory enable row level security;
drop policy if exists "study directory public read" on public.study_directory;
create policy "study directory public read" on public.study_directory for select using(is_active=true or public.is_super_admin());
drop policy if exists "study directory super insert" on public.study_directory;
create policy "study directory super insert" on public.study_directory for insert to authenticated with check(public.is_super_admin());
drop policy if exists "study directory super update" on public.study_directory;
create policy "study directory super update" on public.study_directory for update to authenticated using(public.is_super_admin()) with check(public.is_super_admin());
drop policy if exists "study directory super delete" on public.study_directory;
create policy "study directory super delete" on public.study_directory for delete to authenticated using(public.is_super_admin());
grant select on public.study_directory to anon;
grant select,insert,update,delete on public.study_directory to authenticated;
