-- HA Marketing - Super Admin Shop Permission Fix
-- Run ONCE in Supabase SQL Editor. Safe to run more than once.

-- Principal Super Admin used by this HA Marketing project.
-- This keeps the existing account as active Super Admin.
insert into public.app_admins(user_id,is_super_admin,is_active,created_by)
values(
  'f65185bb-1761-42c0-b358-1b0277555e24'::uuid,
  true,
  true,
  'f65185bb-1761-42c0-b358-1b0277555e24'::uuid
)
on conflict(user_id) do update set
  is_super_admin=true,
  is_active=true,
  updated_at=now();

-- Reliable checks that do not depend on client-side table visibility.
create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.app_admins a
    where a.user_id=auth.uid()
      and a.is_active=true
      and a.is_super_admin=true
  );
$$;
grant execute on function public.is_super_admin() to authenticated;

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.app_admins a
    where a.user_id=auth.uid() and a.is_active=true
  );
$$;
grant execute on function public.is_app_admin() to authenticated;

-- Let every admin read their own admin record, and Super Admin read all admins.
alter table public.app_admins enable row level security;
drop policy if exists "admins read own row" on public.app_admins;
create policy "admins read own row"
on public.app_admins for select to authenticated
using(user_id=auth.uid() or public.is_super_admin());

-- Shop permissions + cards.
create table if not exists public.shop_admin_permissions(
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  section_key text not null,
  can_manage boolean not null default true,
  created_at timestamptz not null default now(),
  primary key(admin_user_id,section_key)
);

create table if not exists public.shop_businesses(
  id bigint generated by default as identity primary key,
  section_key text not null,
  name text not null,
  location_text text not null,
  image_url text,
  description text,
  map_url text,
  page_url text,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.can_manage_shop_section(p_section text)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select public.is_super_admin() or exists(
    select 1
    from public.app_admins a
    join public.shop_admin_permissions p on p.admin_user_id=a.user_id
    where a.user_id=auth.uid()
      and a.is_active=true
      and p.section_key=p_section
      and p.can_manage=true
  );
$$;
grant execute on function public.can_manage_shop_section(text) to authenticated,anon;

alter table public.shop_admin_permissions enable row level security;
alter table public.shop_businesses enable row level security;

drop policy if exists "shop permissions super read" on public.shop_admin_permissions;
create policy "shop permissions super read"
on public.shop_admin_permissions for select to authenticated
using(public.is_super_admin() or admin_user_id=auth.uid());

drop policy if exists "shop businesses public read" on public.shop_businesses;
create policy "shop businesses public read"
on public.shop_businesses for select
using(is_active=true or public.can_manage_shop_section(section_key));

drop policy if exists "shop businesses scoped insert" on public.shop_businesses;
create policy "shop businesses scoped insert"
on public.shop_businesses for insert to authenticated
with check(public.can_manage_shop_section(section_key) and created_by=auth.uid());

drop policy if exists "shop businesses scoped update" on public.shop_businesses;
create policy "shop businesses scoped update"
on public.shop_businesses for update to authenticated
using(public.can_manage_shop_section(section_key))
with check(public.can_manage_shop_section(section_key));

drop policy if exists "shop businesses scoped delete" on public.shop_businesses;
create policy "shop businesses scoped delete"
on public.shop_businesses for delete to authenticated
using(public.can_manage_shop_section(section_key));

-- Storage bucket/policies for shop images.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('shop-images','shop-images',true,6291456,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=true,file_size_limit=6291456,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "shop images scoped insert" on storage.objects;
create policy "shop images scoped insert" on storage.objects for insert to authenticated
with check(bucket_id='shop-images' and public.can_manage_shop_section((storage.foldername(name))[1]));

drop policy if exists "shop images scoped update" on storage.objects;
create policy "shop images scoped update" on storage.objects for update to authenticated
using(bucket_id='shop-images' and public.can_manage_shop_section((storage.foldername(name))[1]));

drop policy if exists "shop images scoped delete" on storage.objects;
create policy "shop images scoped delete" on storage.objects for delete to authenticated
using(bucket_id='shop-images' and public.can_manage_shop_section((storage.foldername(name))[1]));
