-- =========================================================
-- HA Marketing - الإصلاح الأساسي لصلاحيات العمل
-- بائع / متجر / مقدم خدمة / ملعب وجم / ألعاب / تكسي / تكتك / مندوب
-- شغّل هذا الملف مرة واحدة في Supabase > SQL Editor
-- =========================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------
-- 1) جدول طلبات الصلاحيات
-- ---------------------------------------------------------
create table if not exists public.marketplace_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role_type text not null,
  display_name text,
  phone text,
  governorate text,
  address text,
  details text,
  status text not null default 'pending',
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.marketplace_applications add column if not exists user_id uuid;
alter table public.marketplace_applications add column if not exists role_type text;
alter table public.marketplace_applications add column if not exists display_name text;
alter table public.marketplace_applications add column if not exists phone text;
alter table public.marketplace_applications add column if not exists governorate text;
alter table public.marketplace_applications add column if not exists address text;
alter table public.marketplace_applications add column if not exists details text;
alter table public.marketplace_applications add column if not exists status text default 'pending';
alter table public.marketplace_applications add column if not exists admin_note text;
alter table public.marketplace_applications add column if not exists created_at timestamptz default now();
alter table public.marketplace_applications add column if not exists updated_at timestamptz default now();

-- لا نحتاج UNIQUE(user_id,role_type) لأن الطلب يمر عبر RPC آمن.
create index if not exists marketplace_apps_user_idx
  on public.marketplace_applications(user_id);

create index if not exists marketplace_apps_role_status_idx
  on public.marketplace_applications(role_type,status);

-- ---------------------------------------------------------
-- 2) جدول بيانات النقل إن لم يكن موجوداً
-- ---------------------------------------------------------
create table if not exists public.transport_profiles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_type text not null,
  full_name text,
  phone text,
  vehicle_type text,
  vehicle_model text,
  vehicle_color text,
  plate_number text,
  governorate text,
  status text not null default 'pending',
  updated_at timestamptz not null default now()
);

alter table public.transport_profiles add column if not exists user_id uuid;
alter table public.transport_profiles add column if not exists role_type text;
alter table public.transport_profiles add column if not exists full_name text;
alter table public.transport_profiles add column if not exists phone text;
alter table public.transport_profiles add column if not exists vehicle_type text;
alter table public.transport_profiles add column if not exists vehicle_model text;
alter table public.transport_profiles add column if not exists vehicle_color text;
alter table public.transport_profiles add column if not exists plate_number text;
alter table public.transport_profiles add column if not exists governorate text;
alter table public.transport_profiles add column if not exists status text default 'pending';
alter table public.transport_profiles add column if not exists updated_at timestamptz default now();

create index if not exists transport_profiles_user_role_idx
  on public.transport_profiles(user_id,role_type);

-- ---------------------------------------------------------
-- 3) دالة أدمن آمنة
-- تستخدم is_super_admin() الحالية إذا كانت موجودة
-- ---------------------------------------------------------
create or replace function public.ha_is_admin()
returns boolean
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v boolean := false;
begin
  if to_regprocedure('public.is_super_admin()') is not null then
    execute 'select public.is_super_admin()' into v;
    return coalesce(v,false);
  end if;
  return false;
end;
$$;

grant execute on function public.ha_is_admin() to authenticated;

-- ---------------------------------------------------------
-- 4) إرسال/تحديث طلب صلاحية واحد من داخل التطبيق
-- هذه هي الدالة التي تعتمد عليها كل الأنواع
-- ---------------------------------------------------------
create or replace function public.request_marketplace_role(
  p_role text,
  p_display_name text default null,
  p_phone text default null,
  p_governorate text default null,
  p_address text default null,
  p_details text default null,
  p_vehicle_type text default null,
  p_vehicle_model text default null,
  p_vehicle_color text default null,
  p_plate_number text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid := auth.uid();
  v_id text;
  v_status text;
  v_transport_count integer := 0;
begin
  if v_uid is null then
    raise exception 'يجب تسجيل الدخول أولاً';
  end if;

  if p_role not in (
    'seller',
    'service_provider',
    'sports_manager',
    'games_manager',
    'taxi_driver',
    'delivery_driver'
  ) then
    raise exception 'نوع الصلاحية غير صحيح: %', p_role;
  end if;

  -- نستخدم آخر طلب لنفس الدور إن وجد.
  select id::text,status
    into v_id,v_status
  from public.marketplace_applications
  where user_id=v_uid
    and role_type=p_role
  order by created_at desc nulls last
  limit 1;

  if v_id is null then
    insert into public.marketplace_applications(
      user_id,role_type,display_name,phone,governorate,address,details,status,updated_at
    )
    values(
      v_uid,p_role,p_display_name,p_phone,p_governorate,p_address,p_details,'pending',now()
    )
    returning id::text,status into v_id,v_status;
  else
    -- إذا الصلاحية مقبولة لا نلغيها بسبب إعادة فتح النموذج.
    update public.marketplace_applications
    set
      display_name=coalesce(p_display_name,display_name),
      phone=coalesce(p_phone,phone),
      governorate=coalesce(p_governorate,governorate),
      address=coalesce(p_address,address),
      details=coalesce(p_details,details),
      status=case when status='approved' then 'approved' else 'pending' end,
      admin_note=case when status='approved' then admin_note else null end,
      updated_at=now()
    where id::text=v_id
    returning status into v_status;
  end if;

  -- سائق/مندوب: خزّن بيانات المركبة كـ pending بانتظار موافقة الإدارة.
  if p_role in ('taxi_driver','delivery_driver') then

    update public.transport_profiles
    set
      full_name=coalesce(p_display_name,full_name),
      phone=coalesce(p_phone,phone),
      vehicle_type=coalesce(p_vehicle_type,vehicle_type),
      vehicle_model=coalesce(p_vehicle_model,vehicle_model),
      vehicle_color=coalesce(p_vehicle_color,vehicle_color),
      plate_number=coalesce(p_plate_number,plate_number),
      governorate=coalesce(p_governorate,governorate),
      status=case when status='approved' then 'approved' else 'pending' end,
      updated_at=now()
    where user_id=v_uid
      and role_type=p_role;

    get diagnostics v_transport_count = row_count;

    if v_transport_count=0 then
      insert into public.transport_profiles(
        user_id,role_type,full_name,phone,vehicle_type,vehicle_model,
        vehicle_color,plate_number,governorate,status,updated_at
      )
      values(
        v_uid,p_role,p_display_name,p_phone,p_vehicle_type,p_vehicle_model,
        p_vehicle_color,p_plate_number,p_governorate,'pending',now()
      );
    end if;

  end if;

  return jsonb_build_object(
    'ok',true,
    'id',v_id,
    'role_type',p_role,
    'status',v_status
  );
end;
$$;

grant execute on function public.request_marketplace_role(
  text,text,text,text,text,text,text,text,text,text
) to authenticated;

-- ---------------------------------------------------------
-- 5) التحقق من الصلاحية المعتمدة
-- ---------------------------------------------------------
create or replace function public.has_approved_role(p_role text)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select
    public.ha_is_admin()
    or exists(
      select 1
      from public.marketplace_applications m
      where m.user_id=auth.uid()
        and m.role_type=p_role
        and m.status='approved'
    )
    or (
      p_role in ('taxi_driver','delivery_driver')
      and exists(
        select 1
        from public.transport_profiles t
        where t.user_id=auth.uid()
          and t.role_type=p_role
          and t.status='approved'
      )
    );
$$;

grant execute on function public.has_approved_role(text) to authenticated;

-- ---------------------------------------------------------
-- 6) مراجعة الأدمن للطلب
-- ID كنص حتى يشتغل سواء كان bigint أو uuid
-- ---------------------------------------------------------
create or replace function public.admin_review_marketplace_application(
  p_id text,
  p_status text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid;
  v_role text;
begin
  if not public.ha_is_admin() then
    raise exception 'هذه العملية للأدمن الرئيسي فقط';
  end if;

  if p_status not in ('pending','approved','rejected','suspended') then
    raise exception 'حالة الطلب غير صحيحة';
  end if;

  update public.marketplace_applications
  set status=p_status,
      admin_note=p_note,
      updated_at=now()
  where id::text=p_id
  returning user_id,role_type into v_uid,v_role;

  if v_uid is null then
    raise exception 'الطلب غير موجود';
  end if;

  if v_role in ('taxi_driver','delivery_driver') then
    update public.transport_profiles
    set status=p_status,
        updated_at=now()
    where user_id=v_uid
      and role_type=v_role;
  end if;

  return jsonb_build_object(
    'ok',true,
    'id',p_id,
    'status',p_status,
    'role_type',v_role
  );
end;
$$;

grant execute on function public.admin_review_marketplace_application(
  text,text,text
) to authenticated;

-- ---------------------------------------------------------
-- 7) RLS لطلبات الصلاحيات
-- ---------------------------------------------------------
alter table public.marketplace_applications enable row level security;

drop policy if exists "market apps own read" on public.marketplace_applications;
drop policy if exists "market apps admin read" on public.marketplace_applications;
drop policy if exists "market apps own insert" on public.marketplace_applications;
drop policy if exists "market apps own update" on public.marketplace_applications;

create policy "market apps own read"
on public.marketplace_applications
for select
to authenticated
using(
  user_id=auth.uid()
  or public.ha_is_admin()
);

-- الإضافة والتحديث تتم عبر request_marketplace_role() فقط.
grant select on public.marketplace_applications to authenticated;
revoke insert,update,delete on public.marketplace_applications from authenticated;

-- ---------------------------------------------------------
-- 8) RLS لبيانات النقل
-- ---------------------------------------------------------
alter table public.transport_profiles enable row level security;

drop policy if exists "transport profile own" on public.transport_profiles;
drop policy if exists "transport profile insert" on public.transport_profiles;
drop policy if exists "transport profile update" on public.transport_profiles;

create policy "transport profile own"
on public.transport_profiles
for select
to authenticated
using(
  user_id=auth.uid()
  or public.ha_is_admin()
);

grant select on public.transport_profiles to authenticated;
revoke insert,update,delete on public.transport_profiles from authenticated;

-- ---------------------------------------------------------
-- 9) صلاحية البائع - إنشاء وإدارة متجره
-- ---------------------------------------------------------
do $$
begin
  if to_regclass('public.shop_businesses') is not null then
    execute 'alter table public.shop_businesses enable row level security';
    execute 'drop policy if exists "seller own businesses" on public.shop_businesses';
    execute $p$
      create policy "seller own businesses"
      on public.shop_businesses
      for all
      to authenticated
      using(
        (owner_user_id=auth.uid() and public.has_approved_role('seller'))
        or public.ha_is_admin()
      )
      with check(
        (owner_user_id=auth.uid() and public.has_approved_role('seller'))
        or public.ha_is_admin()
      )
    $p$;
    execute 'grant select,insert,update,delete on public.shop_businesses to authenticated';
  end if;
end $$;

-- ---------------------------------------------------------
-- 10) صلاحية البائع - المنتجات
-- ---------------------------------------------------------
do $$
begin
  if to_regclass('public.products') is not null then
    execute 'alter table public.products enable row level security';
    execute 'drop policy if exists "seller own products" on public.products';
    execute $p$
      create policy "seller own products"
      on public.products
      for all
      to authenticated
      using(
        (seller_user_id=auth.uid() and public.has_approved_role('seller'))
        or public.ha_is_admin()
      )
      with check(
        (seller_user_id=auth.uid() and public.has_approved_role('seller'))
        or public.ha_is_admin()
      )
    $p$;
    execute 'grant select,insert,update,delete on public.products to authenticated';
  end if;
end $$;

-- ---------------------------------------------------------
-- 11) صلاحية مقدم الخدمة
-- ---------------------------------------------------------
do $$
begin
  if to_regclass('public.service_providers') is not null then
    execute 'alter table public.service_providers enable row level security';
    execute 'drop policy if exists "provider own profile" on public.service_providers';
    execute $p$
      create policy "provider own profile"
      on public.service_providers
      for all
      to authenticated
      using(
        (owner_user_id=auth.uid() and public.has_approved_role('service_provider'))
        or public.ha_is_admin()
      )
      with check(
        (owner_user_id=auth.uid() and public.has_approved_role('service_provider'))
        or public.ha_is_admin()
      )
    $p$;
    execute 'grant select,insert,update,delete on public.service_providers to authenticated';
  end if;
end $$;

-- ---------------------------------------------------------
-- 12) فحص سريع
-- ---------------------------------------------------------
select
  'HA permissions core ready' as result,
  to_regclass('public.marketplace_applications') is not null as marketplace_ok,
  to_regclass('public.transport_profiles') is not null as transport_ok;
